// Maintained converted-model and original/candidate evaluation consumer.
// Persisted-model prediction is exclusively class_runtime::Runtime.
#include "class_runtime.hpp"
#include "class_model_dataset.cuh"

nlohmann::json class_runtime_fixture();
struct ClassScore { unsigned long long bad,errors; double accuracy; };
__global__ void score_u32(const u32*predicted,const u32*labels,u64 rows,u32 K,ClassScore*s,unsigned long long*classes,unsigned long long*confusion){
 for(u64 r=u64(blockIdx.x)*blockDim.x+threadIdx.x;r<rows;r+=u64(blockDim.x)*gridDim.x){u32 y=labels[r],p=predicted[r];if(y>=K||p>=K){atomicAdd(&s->bad,1ull);continue;}atomicAdd(&s->errors,u64(y!=p));if(classes)atomicAdd(classes+y,1ull);if(confusion)atomicAdd(confusion+u64(y)*K+p,1ull);}
}
__global__ void native_direct_ids(const float*input,u32*output,u64 rows,u32 K,u32*bad){
 for(u64 r=u64(blockIdx.x)*blockDim.x+threadIdx.x;r<rows;r+=u64(blockDim.x)*gridDim.x){float q=input[r];if(!isfinite(q)||q<0||double(q)>=double(K)||q!=floorf(q)){atomicOr(bad,1u);output[r]=UINT32_MAX;}else output[r]=u32(q);}
}
__global__ void native_softprob_ids(const float*input,u32*output,u64 rows,u32 K,u32*bad){
 for(u64 r=u64(blockIdx.x)*blockDim.x+threadIdx.x;r<rows;r+=u64(blockDim.x)*gridDim.x){u32 winner=0;float best=input[r*K];bool invalid=false;for(u32 k=0;k<K;++k){float q=input[r*K+k];invalid|=!isfinite(q)||q<0||q>1;if(q>best){best=q;winner=k;}}if(invalid)atomicOr(bad,1u);output[r]=winner;}
}
__global__ void contiguous_rows(const float*input,float*output,u64 rows,u64 stride,u32 F){
 for(u64 t=u64(blockIdx.x)*blockDim.x+threadIdx.x;t<rows*u64(F);t+=u64(blockDim.x)*gridDim.x)output[t]=input[(t/F)*stride+t%F];
}
__global__ void finish_class_score(ClassScore*s,u64 rows){if(!blockIdx.x&&!threadIdx.x)s->accuracy=double(rows-s->errors)/double(rows);}
J class_counts(const u32*predicted,const u32*labels,u64 rows,u32 K,bool collect,u64 max_cells){
 Dev<ClassScore>s(1);s.zero();bool cl=collect&&u64(K)<=max_cells,cf=cl&&u64(K)*K<=max_cells;Dev<unsigned long long>classes(cl?K:0),confusion(cf?u64(K)*K:0);classes.zero();confusion.zero();score_u32<<<blocks(rows),256>>>(predicted,labels,rows,K,s.p,classes.p,confusion.p);finish_class_score<<<1,1>>>(s.p,rows);done();auto result=s.at(0);need(!result.bad,"invalid dynamic class/label IDs");J out={{"CUDA_computed",true},{"rows",rows},{"errors",result.errors},{"accuracy",result.accuracy},{"class_counts_collected",cl},{"confusion_collected",cf},{"statistics_cell_capacity",max_cells}};if(cl)out["class_counts"]=classes.get();if(cf)out["confusion_rows_true_columns_predicted"]=confusion.get();return out;
}
J graph_contract(const class_runtime::Metadata&m){return {{"inference_module","native/class_runtime"},{"features",m.features},{"classes",m.classes},{"root",m.root},{"nodes",m.nodes},{"predicates",m.predicates},{"canonical_resident",m.canonical_resident},{"compact_resident",m.compact_resident},{"full_cross_layout_words_equal",m.cross_layout_validated},{"canonical_file_bytes",m.canonical_bytes},{"compact_file_bytes",m.compact_bytes},{"retained_graph_device_bytes",m.device_bytes},{"source_sha256",m.source_sha256},{"canonical_sha256",m.canonical_sha256},{"compact_sha256",m.compact_sha256}};}
class_runtime::Residency residency(const J&p){std::string value=p.value("runtime_residency",std::string("dual"));if(value=="dual")return class_runtime::Residency::dual;if(value=="canonical_only")return class_runtime::Residency::canonical_only;if(value=="compact_only")return class_runtime::Residency::compact_only;throw std::runtime_error("unsupported runtime residency");}
struct ModelInput {std::string canonical,canonical_pin,compact,compact_pin,source;std::vector<std::pair<fs::path,std::string>>pins;};
ModelInput model_input(const J&e){ModelInput in;in.source=e.at("source_sha256");fs::path rp=e.at("runtime_path").get<std::string>();Cpath(rp);auto rb=mn_read(rp);std::string rs=e.at("runtime_sha256");need(sha256(rb)==rs,"runtime pin differs");in.pins.emplace_back(rp,rs);if(rb.substr(0,8)=="CLSGDAG1"){in.canonical=rb;in.canonical_pin=rs;}else{need(rb.substr(0,8)=="CLSG64B1","unsupported runtime format");in.compact=rb;in.compact_pin=rs;fs::path cp=e.at("canonical_runtime_path").get<std::string>();Cpath(cp);in.canonical=mn_read(cp);in.canonical_pin=e.at("canonical_runtime_sha256");need(sha256(in.canonical)==in.canonical_pin,"canonical pin differs");in.pins.emplace_back(cp,in.canonical_pin);}return in;}
J evaluate(const fs::path&planpath,const std::string&pin,const fs::path&out,const fs::path&exe){
 Cpath(planpath);auto pb=mn_read(planpath);need(sha256(pb)==pin,"plan differs");auto p=J::parse(pb);need((p.at("format")=="mnist-compact64-runtime-evaluation-plan-1"||p.at("format")=="class-model-evaluation-plan-1")&&p.at("TEST_read")==false&&p.at("selection_performed")==false&&p.at("training_performed")==false,"evaluation protocol");need(sha256(mn_read(exe))==p.at("executable_sha256").get<std::string>(),"executable differs");u32 threads=inference_block_size(p);auto started=std::chrono::steady_clock::now();clean_output(out);auto data=load_model_dataset(p,out);
 fs::path lib=p.at("native_library_path").get<std::string>();need(sha256(mn_read(lib))==native_class_reference::library_identity(p),"native library differs");native_class_reference::Api api(lib,data.F);Dev<float>reference_dense(data.stride==data.F?0:data.rows*data.F);const float*nativex=data.x.p;if(reference_dense.n){contiguous_rows<<<blocks(reference_dense.n),256>>>(data.x.p,reference_dense.p,data.rows,data.stride,data.F);done();nativex=reference_dense.p;}
 J models=J::array();need(!p.at("evaluations").empty()&&p.at("evaluations").size()<=32,"evaluation count");
 for(const auto&e:p.at("evaluations")){
  fs::path sp=e.at("source_path").get<std::string>();Cpath(sp);auto sb=mn_read(sp);std::string ss=e.at("source_sha256");need(sha256(sb)==ss,"source pin differs");auto source=J::parse(sb);std::string objective=source.at("learner").at("objective").at("name");bool direct=objective=="multi:softmax";need(direct||objective=="multi:softprob","multiclass source objective");need(source.at("learner").at("learner_model_param").at("num_feature")==std::to_string(data.F)&&source.at("learner").at("learner_model_param").at("num_class")==std::to_string(data.K),"source/data shape differs");auto input=model_input(e);auto import_started=std::chrono::steady_clock::now();auto runtime=class_runtime::Runtime::load(input.canonical,input.canonical_pin,ss,input.compact,input.compact_pin,residency(p));need(runtime->metadata().features==data.F&&runtime->metadata().classes==data.K,"runtime/data shape differs");J row=e;row["shared_runtime_contract"]=graph_contract(runtime->metadata());row["validation_host_wall_seconds"]=std::chrono::duration<double>(std::chrono::steady_clock::now()-import_started).count();row["class_mismatches"]=0;row["source_objective"]=objective;row["native_prediction_contract"]=direct?"public CUDA direct class IDs":"public CUDA softprob strict first-index argmax";row["inference_timing_performed"]=false;
  std::unique_ptr<class_runtime::Runtime>original;
  if(e.contains("original_canonical_runtime_path")){fs::path op=e.at("original_canonical_runtime_path").get<std::string>();Cpath(op);auto ob=mn_read(op);std::string os=e.at("original_canonical_runtime_sha256");need(sha256(ob)==os,"original canonical differs");input.pins.emplace_back(op,os);original=class_runtime::Runtime::load(ob,os,ss,{},{},class_runtime::Residency::canonical_only);need(original->metadata().features==data.F&&original->metadata().classes==data.K,"original/data shape differs");row["original_shared_runtime_contract"]=graph_contract(original->metadata());}
  api.load(sp);
  for(u32 split=0;split<2;++split){u64 first=split?data.fit_rows:0,rows=split?data.valid_rows:data.fit_rows;Dev<u32>native(rows),actual(rows),bad(1);bad.zero();auto values=api.classes(nativex+first*data.F,rows,direct?1:data.K);if(direct)native_direct_ids<<<blocks(rows),256>>>(values,native.p,rows,data.K,bad.p);else native_softprob_ids<<<blocks(rows),256>>>(values,native.p,rows,data.K,bad.p);done();need(!bad.at(0),"native direct class IDs invalid");class_runtime::DenseBatch batch{data.x.p,data.x.n,first,rows,data.stride};runtime->verify(batch,native.p,rows,threads);auto layout=runtime->metadata().compact_resident?class_runtime::Layout::compact8:class_runtime::Layout::canonical16;runtime->predict(batch,{actual.p,actual.n},layout,class_runtime::Traversal::validated,threads);auto truth=data.labels.p+first;J scored={{"native",class_counts(native.p,truth,rows,data.K,p.value("collect_statistics",true),p.value("statistics_cell_capacity",u64(1048576)))},{"runtime",class_counts(actual.p,truth,rows,data.K,p.value("collect_statistics",true),p.value("statistics_cell_capacity",u64(1048576)))},{"class_mismatches",0},{"shared_resident_variants_native_comparison",true}};
   if(original){original->verify(batch,native.p,rows,threads);scored["original_shared_native_class_mismatches"]=0;}row[split?"VALID":"FIT"]=scored;
  }
  for(const auto&[path,expected]:input.pins)need(sha256(mn_read(path))==expected,"runtime changed during evaluation");need(sha256(mn_read(sp))==ss,"source changed during evaluation");models.push_back(row);
 }
 recheck_model_dataset(data);need(sha256(mn_read(lib))==p.at("native_library_sha256").get<std::string>()&&sha256(mn_read(exe))==p.at("executable_sha256").get<std::string>()&&sha256(mn_read(planpath))==pin,"final evaluation pins differ");J result={{"format","class-model-evaluation-result-1"},{"complete",true},{"CUDA_executed",true},{"CPU_predictions",false},{"TEST_read",false},{"training_performed",false},{"selection_performed",false},{"dataset",data.binding},{"features",data.F},{"classes",data.K},{"FIT_rows",data.fit_rows},{"VALID_rows",data.valid_rows},{"models",models},{"class_mismatches",0},{"plan_sha256",pin},{"executable_sha256",p.at("executable_sha256")},{"native_library_sha256",p.at("native_library_sha256").get<std::string>()},{"persisted_model_inference","native/class_runtime::Runtime"},{"inference_block_size",threads},{"inference_timing_performed",false},{"consumer_peak_owned_CUDA_bytes_excluding_runtime_native_and_Thrust",peak_owned},{"seconds_before_receipt",std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count()}};atomic_json(out/"result.json",result);atomic_json(out/"result-seal.json",{{"sealed",true},{"result_sha256",sha256(mn_read(out/"result.json"))},{"plan_sha256",pin},{"executable_sha256",p.at("executable_sha256")},{"TEST_read",false}});return result;
}
__global__ void dense_consumer_probe(float*x,u32*y,u64 rows,u32 F,u64 stride){for(u64 r=u64(blockIdx.x)*blockDim.x+threadIdx.x;r<rows;r+=u64(blockDim.x)*gridDim.x){for(u64 f=0;f<stride;++f)x[r*stride+f]=f==0?(r%2?-1.f:0.f):f==F-1?(r%3?0.f:1.f):0.f;y[r]=r%3?u32(r%2?0:1):2;}}
J fixture(const fs::path&out){J result={{"complete",true},{"CUDA_executed",true},{"CPU_predictions",false},{"TEST_read",false},{"shared_runtime_fixture",class_runtime_fixture()},{"IDX_packing_scoring_fixture",mnist_fixture()},{"native_direct_class_fixture",direct_fixture()}};
 const u32 F=3,K=3;const u64 rows=257,stride=5;Dev<float>x(rows*stride);Dev<u32>y(rows);dense_consumer_probe<<<blocks(rows),256>>>(x.p,y.p,rows,F,stride);done();auto hx=x.get();auto hy=y.get();std::string xb(reinterpret_cast<const char*>(hx.data()),hx.size()*4),yb(reinterpret_cast<const char*>(hy.data()),hy.size()*4);atomic_text(out/"fixture-values.fp32",xb);atomic_text(out/"fixture-labels.u32",yb);J d={{"format","dense-fp32-u32-class-labels-1"},{"features",F},{"classes",K},{"rows",rows},{"row_stride",stride},{"FIT_rows",128},{"VALID_rows",129},{"values_path",(out/"fixture-values.fp32").string()},{"values_sha256",sha256(xb)},{"labels_path",(out/"fixture-labels.u32").string()},{"labels_sha256",sha256(yb)},{"preprocessing","synthetic CUDA fixture; model-input FP32"},{"TEST_read",false}};auto loaded=load_model_dataset(J{{"dataset",d}},out);std::string model="CLSGDAG1";for(u32 v:{1u,F,K,4u,5u,1u})model.append(reinterpret_cast<const char*>(&v),4);model.append(32,'\0');for(auto n:std::vector<std::array<u32,4>>{{UINT32_MAX,0,0,0},{UINT32_MAX,1,0,0},{UINT32_MAX,2,0,0},{0,0,0,1},{F-1,1,3,2}})for(u32 v:n)model.append(reinterpret_cast<const char*>(&v),4);auto runtime=class_runtime::Runtime::load(model,sha256(model),std::string(64,'0'));class_runtime::DenseBatch batch{loaded.x.p,loaded.x.n,0,rows,stride};runtime->verify(batch,loaded.labels.p,loaded.labels.n);Dev<u32>pred(rows);runtime->predict(batch,{pred.p,pred.n},class_runtime::Layout::compact8,class_runtime::Traversal::validated);auto counts=class_counts(pred.p,loaded.labels.p,rows,K,true,1024);need(counts.at("errors")==0,"dense consumer scoring differs");result["dense_dataset_consumer"]={{"dataset",loaded.binding},{"scores",counts},{"graph",graph_contract(runtime->metadata())}};recheck_model_dataset(loaded);return result;
}
int main(int argc,char**argv){try{static_assert(sizeof(float)==4&&sizeof(u32)==4&&std::endian::native==std::endian::little);need((argc==3&&std::string(argv[1])=="fixture")||(argc==5&&std::string(argv[1])=="evaluate"),"fixture OUT | evaluate PLAN SHA OUT");fs::path out=fs::absolute(argv[argc-1]);Cpath(out);need(!fs::exists(out),"output exists");ck(cudaSetDevice(0),"device");J result;if(argc==3){clean_output(out);result=fixture(out);atomic_json(out/"result.json",result);}else result=evaluate(argv[2],argv[3],out,fs::canonical("/proc/self/exe"));std::cout<<result.dump(2)<<'\n';return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}