#include "class_rank_xai_export.hpp"
#include "class_io.hpp"
#include <algorithm>
#include <bit>
#include <cmath>
#include <cstring>
#include <fcntl.h>
#include <unistd.h>
#include <cerrno>
#include <climits>
#include <set>

namespace rank_xai_export {namespace {
using J=dpnative::json; namespace fs=std::filesystem;
void need(bool b,const char*s){if(!b)throw std::runtime_error(s);}
std::string hx(std::uint32_t v){std::ostringstream s;s<<std::hex<<std::setfill('0')<<std::setw(8)<<v;return "0x"+s.str();}
std::string fp(std::uint32_t b){std::ostringstream s;s<<std::setprecision(std::numeric_limits<float>::max_digits10)<<std::bit_cast<float>(b);return s.str();}
U number(const J&j){need(j.is_number_unsigned(),"expected unsigned metadata");return j.get<U>();}
std::int32_t integer(const J&j){need(j.is_number_integer(),"expected integer metadata");if(j.is_number_unsigned()){auto x=j.get<U>();need(x<=INT32_MAX,"integer metadata overflow");return std::int32_t(x);}auto x=j.get<std::int64_t>();need(x>=INT32_MIN&&x<=INT32_MAX,"integer metadata overflow");return std::int32_t(x);}
std::uint32_t word(const J&j){auto x=number(j);need(x<=UINT32_MAX,"FP32 word overflow");return std::uint32_t(x);}
U plus(U a,U b){need(a<=UINT64_MAX-b,"metadata count overflow");return a+b;}
std::string bigplus(std::string a,std::string b){std::string c;int carry=0;std::size_t i=a.size(),j=b.size();while(i||j||carry){int v=carry+(i?a[--i]-'0':0)+(j?b[--j]-'0':0);c+=char('0'+v%10);carry=v/10;}std::reverse(c.begin(),c.end());return c;}
J box(const codec::tasks::Box&b){return {{"lo",b.lo},{"hi",b.hi},{"allowed",b.allowed}};}
std::string name(GateKind g){switch(g){case GateKind::leaf:return "leaf";case GateKind::constant_false:return "constant_false";case GateKind::constant_true:return "constant_true";case GateKind::numeric_less:return "numeric_raw_less";case GateKind::category_less:return "category_onehot_less";}throw std::runtime_error("unknown gate kind");}
J capabilities(bool smooth){return {
 {"hard_equation_export",{{"implemented",true},{"scope","shared axis/class DAG structural export; no CPU prediction evaluation"}}},
 {"smooth_equation_export",{{"implemented",smooth},{"available",true},{"scope","optional symbolic positive numeric temperatures; altered classifier"}}},
 {"gpu_prediction_and_path_trace",{{"implemented",false},{"scope","separate GPU evaluator required"}}},
 {"contrastive_explanations",{{"implemented",false}}},
 {"counterfactual_search",{{"implemented",false},{"scope","requires domain-feasible search and exact verification"}}},
 {"feature_effect",{{"implemented",false},{"scope","requires declared baseline/domain and GPU evaluation"}}},
 {"fuzzy_gradients",{{"implemented",false},{"scope","symbolic equations only; continuous numeric derivative evaluator pending"}}},
 {"equivalence",{{"implemented",true},{"scope","exact codec-word reconstruction only; not a fresh source/native proof or smooth equivalence"}}}
};}
J gate(const Node&n,bool smooth){J j={{"kind",name(n.gate)},{"feature",n.feature},{"stored_rank_or_onehot_cut_bits",n.stored_cut_bits},{"stored_cut_hex",hx(n.stored_cut_bits)},{"raw_threshold_bits",n.raw_threshold_bits},{"raw_threshold_hex",hx(n.raw_threshold_bits)},{"strict_left",true}};
 if(n.gate==GateKind::numeric_less||n.gate==GateKind::category_less){j["hard_expression"]="I[x_"+std::to_string(n.feature)+" < fp32("+hx(n.raw_threshold_bits)+")]";j["threshold_decimal_display"]=fp(n.raw_threshold_bits);j["equality_child"]="right";if(smooth&&n.gate==GateKind::numeric_less){j["smooth_expression"]="sigmoid((fp32("+hx(n.raw_threshold_bits)+") - x_"+std::to_string(n.feature)+") / tau_"+std::to_string(n.feature)+")";j["temperature_constraint"]="tau_"+std::to_string(n.feature)+" > 0";}else j["smooth_expression"]=j["hard_expression"];
 }else{j["hard_expression"]=n.gate==GateKind::constant_true?"1":"0";j["smooth_expression"]=j["hard_expression"];}
 return j;
}
J payload(const codec::Model&m){J nodes=J::array();for(const auto&n:m.nodes)nodes.push_back({{"id",n.id},{"left",n.left},{"right",n.right},{"kind",n.kind},{"feature",n.feature},{"label",n.label},{"cut_bits",n.cut_bits},{"first_term",n.first_term},{"term_count",n.term_count},{"threshold_bits",n.threshold_bits}});
 return {{"source_sha256",m.source_sha256},{"rank_sha256",m.rank_sha256},{"scope",box(m.scope)},{"rank_cut_bits",m.rank_cut_bits},{"root",m.root},{"nodes",nodes},{"terms",J::array()}};
}
codec::Model reconstruct(const J&p){
 codec::Model m;m.source_sha256=p.at("source_sha256").get<std::string>();m.rank_sha256=p.at("rank_sha256").get<std::string>();m.root=number(p.at("root"));auto&b=p.at("scope");need(b.at("lo").is_array()&&b.at("lo").size()==10&&b.at("hi").is_array()&&b.at("hi").size()==10,"scope dimensions");for(unsigned i=0;i<10;++i){m.scope.lo[i]=integer(b.at("lo")[i]);m.scope.hi[i]=integer(b.at("hi")[i]);}m.scope.allowed=number(b.at("allowed"));auto&r=p.at("rank_cut_bits");need(r.is_array()&&r.size()==10,"rank dimensions");for(unsigned i=0;i<10;++i){need(r[i].is_array(),"rank column");for(auto&w:r[i])m.rank_cut_bits[i].push_back(word(w));}need(p.at("terms").is_array()&&p.at("terms").empty(),"unsupported arithmetic terms");need(p.at("nodes").is_array(),"node array");for(auto&v:p.at("nodes")){codec::collect::dl::Node n;n.id=number(v.at("id"));n.left=number(v.at("left"));n.right=number(v.at("right"));n.kind=integer(v.at("kind"));n.feature=integer(v.at("feature"));n.label=integer(v.at("label"));n.cut_bits=word(v.at("cut_bits"));n.first_term=number(v.at("first_term"));n.term_count=word(v.at("term_count"));n.threshold_bits=number(v.at("threshold_bits"));m.nodes.push_back(n);}return m;
}
J equations(const codec::Model&source,const Model&m,bool smooth){J eq=J::array();for(const auto&n:m.nodes){J e={{"id",n.id},{"symbol","v_"+std::to_string(n.id)},{"kind",n.kind}};if(n.gate==GateKind::leaf){std::array<int,7>v{};v[n.label]=1;e["label"]=n.label;e["onehot"]=v;e["hard_expression"]="e_"+std::to_string(n.label);e["smooth_expression"]=e["hard_expression"];}else{e["left"]=n.left;e["right"]=n.right;e["gate"]=gate(n,smooth);e["hard_expression"]="g_"+std::to_string(n.id)+" * v_"+std::to_string(n.left)+" + (1 - g_"+std::to_string(n.id)+") * v_"+std::to_string(n.right);e["smooth_expression"]=e["hard_expression"];}eq.push_back(e);}
 return {{"format","CLSRMDL1-shared-equations-1"},{"runtime_sha256",m.runtime_sha256},{"source_sha256",m.source_sha256},{"rank_sha256",m.rank_sha256},{"root",m.root},{"hard_semantics","exact strict hard-gated DAG; each vector has seven components"},{"numeric_interpretation","finite FP32 raw x; rank is number of sorted source cuts <= x; bits authoritative"},{"domain",{{"features",54},{"numeric_features",10},{"numeric_values","all finite FP32, including fractional values and both zeros"},{"categorical_groups",J::array({J{{"first_feature",10},{"size",4}},J{{"first_feature",14},{"size",40}}})},{"onehot","exactly one 1 per group; all other group entries exactly 0"},{"scope_rank_box",box(m.scope)},{"out_of_scope","unsupported; reject before prediction"}}},{"class_rule",{{"classes",7},{"hard","unique one-hot class at root"},{"smooth","first maximum component; smallest class index on exact ties"}}},{"smooth",{{"enabled",smooth},{"changes_classifier",smooth},{"numeric_gate","sigmoid((t-x_f)/tau_f), real symbolic tau_f > 0"},{"categorical_gate","unchanged exact one-hot comparison"},{"accuracy_claim",false},{"source_equivalence_claim",false},{"floating_point_evaluator_qualified",false}}},{"supported_node_kinds",J::array({"axis","class_leaf"})},{"unsupported_node_kinds",J::array({"ordered_arithmetic_plane"})},{"shared_equations",eq},{"codec_payload",payload(source)},{"scientist_capabilities",capabilities(smooth)},{"authority",{{"fresh_source_proof",false},{"CPU_predictions_evaluated",false},{"structural_reconstruction",true}}}};
}
J inspect(const Model&m){std::vector<U>degree(m.nodes.size()),depth(m.nodes.size());std::vector<std::string>expanded(m.nodes.size());std::array<U,54>features{};std::array<U,7>labels{};U leaves=0,axes=0,edges=0,constant=0,maxdepth=0;for(const auto&n:m.nodes){if(n.gate==GateKind::leaf){++leaves;++labels[n.label];expanded[n.id]="1";}else{++axes;++features[n.feature];degree[n.left]=plus(degree[n.left],1);degree[n.right]=plus(degree[n.right],1);edges=plus(edges,2);depth[n.id]=plus(std::max(depth[n.left],depth[n.right]),1);expanded[n.id]=bigplus("1",bigplus(expanded[n.left],expanded[n.right]));if(n.gate==GateKind::constant_true||n.gate==GateKind::constant_false)++constant;}maxdepth=std::max(maxdepth,depth[n.id]);}
 U shared=0,maxdegree=0;for(auto x:degree){shared+=x>1;maxdegree=std::max(maxdegree,x);}bool full=m.scope.allowed==((U(1)<<44)-1);for(unsigned i=0;i<10;++i){const auto&cuts=m.rank_cut_bits[i];const int reachable_min=!cuts.empty()&&cuts.front()==0xff7fffffu?1:0;full=full&&m.scope.lo[i]<=reachable_min&&U(m.scope.hi[i])==cuts.size();}
 return {{"format","CLSRMDL1-XAI-inspect-1"},{"runtime_sha256",m.runtime_sha256},{"source_sha256",m.source_sha256},{"rank_sha256",m.rank_sha256},{"runtime_bytes",m.runtime_bytes},{"root",m.root},{"stored_nodes",m.nodes.size()},{"reachable_nodes",m.nodes.size()},{"all_nodes_reachable",true},{"acyclic_child_before_parent",true},{"axis_nodes",axes},{"leaf_nodes",leaves},{"stored_terms",0},{"edges",edges},{"nodes_with_multiple_incoming_edges",shared},{"maximum_indegree",maxdegree},{"depth_decisions",depth[m.root]},{"maximum_node_depth",maxdepth},{"unfolded_nodes_decimal",expanded[m.root]},{"physical_path_expansion_performed",false},{"constant_gates",constant},{"feature_gate_counts",features},{"leaf_class_counts",labels},{"full_forest_domain_scope",full},{"full_source_correctness_replayed",false}};
}
std::string text(const Model&m,bool smooth){std::ostringstream s;s<<"Exact shared DAG equations\n\nRuntime SHA-256: "<<m.runtime_sha256<<"\nSource SHA-256: "<<m.source_sha256<<"\nRank table SHA-256: "<<m.rank_sha256<<"\n\nDomain: finite FP32 numeric x_0..x_9; exact one-hot groups x_10..x_13 and x_14..x_53.\nThe scope rank box is included in equations.json. Reject inputs outside that scope.\nEvery fp32(0x........) means the exact IEEE-754 binary32 word; decimals are display only.\nNumeric rank r is the number of stored source cuts <= x. Equality always takes the right child.\nLeaf e_k is the seven-component one-hot vector for class k. Define each shared v once:\n\n";for(auto&n:m.nodes){if(n.gate==GateKind::leaf)s<<"v_"<<n.id<<" = e_"<<n.label<<"\n";else{s<<"g_"<<n.id<<" = ";if(n.gate==GateKind::constant_false)s<<"0";else if(n.gate==GateKind::constant_true)s<<"1";else s<<"I[x_"<<n.feature<<" < fp32("<<hx(n.raw_threshold_bits)<<")]  (threshold "<<fp(n.raw_threshold_bits)<<")";s<<"\nv_"<<n.id<<" = g_"<<n.id<<" * v_"<<n.left<<" + (1-g_"<<n.id<<") * v_"<<n.right<<"\n";}}
 s<<"\nHard output: v_"<<m.root<<"; its unique one-hot position is the class.\n";
 if(smooth)s<<"\nOptional smooth numeric surrogate (ALTERED classifier): replace each nonconstant numeric g_n\nwith sigmoid((t-x_f)/tau_f), with symbolic real tau_f > 0 and the same exact raw threshold t.\nKeep category/constant gates hard and leaf vectors unchanged. The same shared equations define\nseven scores. Class = smallest index attaining the maximum score. This is not a probability\ncalibration, an accuracy claim, or a source-equivalence claim. No floating-point smooth evaluator\nor gradient evaluator is qualified by this export.\n";
 s<<"\nThis artifact is a structural equation export and exact codec reconstruction, not a fresh source proof.\nPrediction traces, contrastive/counterfactual search, feature effects and fuzzy gradients require\nseparate evaluation/verification. See scientist_capabilities in equations.json.\n";return s.str();
}
void durable(const fs::path&p,const std::string&s){auto tmp=p;tmp+=".pending";int fd=::open(tmp.c_str(),O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC,0600);need(fd>=0,"export temporary open failed");try{std::size_t at=0;while(at<s.size()){auto n=::write(fd,s.data()+at,s.size()-at);if(n<0&&errno==EINTR)continue;need(n>0,"export write failed");at+=std::size_t(n);}need(::fsync(fd)==0,"export fsync failed");int z=::close(fd);fd=-1;need(!z,"export close failed");need(::rename(tmp.c_str(),p.c_str())==0,"export rename failed");int d=::open(p.parent_path().c_str(),O_RDONLY|O_DIRECTORY|O_CLOEXEC);need(d>=0,"export directory open failed");int a=::fsync(d),b=::close(d);need(!a&&!b,"export directory sync failed");}catch(...){if(fd>=0)::close(fd);throw;}}
std::string read(const fs::path&p){need(fs::is_regular_file(p)&&!fs::is_symlink(p)&&fs::file_size(p)<=1024ull*1024*1024,"export input absent/oversize/symlink");return dpnative::read_text(p);}
void content_verify(const fs::path&dir,const std::string&runtimehash){auto raw=read(dir/"equations.json");J j=J::parse(raw);auto m=reconstruct(j.at("codec_payload"));auto ir=lower(m);need(ir.runtime_sha256==runtimehash,"reconstructed runtime identity differs");bool smooth=j.at("smooth").at("enabled").get<bool>();need(j==equations(m,ir,smooth),"equation structural reconstruction differs");need(J::parse(read(dir/"inspect.json"))==inspect(ir),"inspection reconstruction differs");need(read(dir/"equations.txt")==text(ir,smooth),"human equation reconstruction differs");}
} // namespace
Model lower(const codec::Model&m){
 auto raw=codec::encode(m);auto checked=codec::decode(raw);(void)checked;need(m.terms.empty(),"unsupported ordered arithmetic plane/terms");
 Model out;out.runtime_sha256=dpnative::sha256(raw);out.source_sha256=m.source_sha256;out.rank_sha256=m.rank_sha256;out.scope=m.scope;out.rank_cut_bits=m.rank_cut_bits;out.root=m.root;out.runtime_bytes=raw.size();out.nodes.reserve(m.nodes.size());
 for(const auto&n:m.nodes){need(n.kind==0||n.kind==2,"unsupported ordered arithmetic plane node");Node t;t.id=n.id;t.left=n.left;t.right=n.right;t.kind=n.kind;t.feature=n.feature;t.label=n.label;t.stored_cut_bits=n.cut_bits;t.raw_threshold_bits=n.cut_bits;if(n.kind==2)t.gate=GateKind::leaf;else{float c=std::bit_cast<float>(n.cut_bits);if(n.feature<10){if(c<=0)t.gate=GateKind::constant_false;else if(double(c)>double(m.rank_cut_bits[n.feature].size()))t.gate=GateKind::constant_true;else{auto k=U(std::ceil(double(c)));need(k>=1&&k<=m.rank_cut_bits[n.feature].size(),"numeric rank threshold mapping invalid");t.raw_threshold_bits=m.rank_cut_bits[n.feature][k-1];t.gate=GateKind::numeric_less;}}else if(c<=0)t.gate=GateKind::constant_false;else if(c>1)t.gate=GateKind::constant_true;else t.gate=GateKind::category_less;}out.nodes.push_back(t);}
 std::vector<unsigned char>reachable(m.nodes.size());reachable[m.root]=1;for(U i=m.nodes.size();i-->0;)if(reachable[i]&&m.nodes[i].kind!=2){reachable[m.nodes[i].left]=1;reachable[m.nodes[i].right]=1;}need(std::all_of(reachable.begin(),reachable.end(),[](auto x){return x==1;}),"runtime contains unreachable nodes");return out;
}
Result write(const fs::path&runtime,const std::string&expected,const fs::path&dir,Options options){
 need(!fs::exists(dir),"output directory must be fresh");auto source=codec::read_model(runtime,expected,options.maximum_runtime_bytes);auto ir=lower(source);need(ir.runtime_sha256==expected,"runtime changed while lowering");auto ej=equations(source,ir,options.smooth_numeric);auto ij=inspect(ir);auto et=text(ir,options.smooth_numeric);auto eraw=ej.dump(2)+"\n",iraw=ij.dump(2)+"\n";
 need(fs::create_directories(dir),"output directory creation failed");durable(dir/"equations.json",eraw);durable(dir/"equations.txt",et);durable(dir/"inspect.json",iraw);content_verify(dir,expected);need(dpnative::sha256(read(runtime))==expected,"runtime changed during export");
 Result r;r.runtime_sha256=expected;r.equations_sha256=dpnative::sha256(eraw);r.text_sha256=dpnative::sha256(et);r.inspect_sha256=dpnative::sha256(iraw);r.nodes=ir.nodes.size();r.runtime_bytes=ir.runtime_bytes;r.export_bytes=plus(plus(eraw.size(),et.size()),iraw.size());r.structural_roundtrip=true;
 J receipt={{"format","CLSRMDL1-XAI-export-result-1"},{"complete",true},{"runtime_sha256",expected},{"source_sha256",ir.source_sha256},{"rank_sha256",ir.rank_sha256},{"equations_sha256",r.equations_sha256},{"text_sha256",r.text_sha256},{"inspect_sha256",r.inspect_sha256},{"runtime_bytes",r.runtime_bytes},{"export_payload_bytes",r.export_bytes},{"nodes",r.nodes},{"structural_roundtrip",true},{"CPU_predictions_evaluated",false},{"GPU_executed",false},{"fresh_source_authority",false},{"smooth_numeric_enabled",options.smooth_numeric},{"accuracy_claim",false}};
 auto result=receipt.dump(2)+"\n";durable(dir/"result.json",result);r.result_sha256=dpnative::sha256(result);verify(dir);return r;
}
void verify(const fs::path&dir){auto r=J::parse(read(dir/"result.json"));need(r.at("format")=="CLSRMDL1-XAI-export-result-1"&&r.at("complete")==true&&r.at("structural_roundtrip")==true&&r.at("CPU_predictions_evaluated")==false&&r.at("GPU_executed")==false&&r.at("fresh_source_authority")==false&&r.at("accuracy_claim")==false,"export result contract differs");need(dpnative::sha256(read(dir/"equations.json"))==r.at("equations_sha256").get<std::string>()&&dpnative::sha256(read(dir/"equations.txt"))==r.at("text_sha256").get<std::string>()&&dpnative::sha256(read(dir/"inspect.json"))==r.at("inspect_sha256").get<std::string>(),"export payload hash differs");auto e=J::parse(read(dir/"equations.json"));auto m=lower(reconstruct(e.at("codec_payload")));need(r.at("source_sha256").get<std::string>()==m.source_sha256&&r.at("rank_sha256").get<std::string>()==m.rank_sha256&&number(r.at("runtime_bytes"))==m.runtime_bytes&&number(r.at("nodes"))==m.nodes.size()&&r.at("smooth_numeric_enabled")==e.at("smooth").at("enabled"),"export receipt identity differs");U bytes=plus(plus(fs::file_size(dir/"equations.json"),fs::file_size(dir/"equations.txt")),fs::file_size(dir/"inspect.json"));need(number(r.at("export_payload_bytes"))==bytes,"export receipt byte count differs");content_verify(dir,r.at("runtime_sha256").get<std::string>());}
} // namespace rank_xai_export

