#include "class_study_checkpoint.hpp"
#include <iostream>
using namespace class_study::checkpoint;
namespace {unsigned checks=0;void test(bool x,const char*m){++checks;require(x,m);}template<class F>void refuses(F f){bool no=false;try{f();}catch(const std::exception&){no=true;}test(no,"metadata/transport refusal missing");}Json state(unsigned trial){std::string b("\0\x80\xff",3);return{{"format","resident-study-checkpoint-1"},{"current_trial",trial},{"phase","conversion"},{"completed_fit_calls",trial+1},{"fixed_trials",Json::array({{{"seed",19}},{{"seed",23}}})},{"retained",Json::array({{{"native",binary("retained native")},{"canonical",binary(b)},{"compact",binary(b)}}})},{"current_native",binary("current native")},{"results",Json::array({{{"evaluation_status","pending"}}})},{"evaluation_completed",0},{"selection_performed",false},{"RL_state",nullptr}};}}
int main(int argc,char**argv){try{require(argc==2,"usage: checks FRESH_DIRECTORY");fs::path root=argv[1];require(root.is_absolute()&&!fs::exists(root),"fresh test root required");auto a=state(1);Coordinator c(root);test(c.save_host(a),"host submission");c.finish();test(c.poll().committed&&!c.poll().failed,"host commit");auto l=Coordinator::load(root);test(l.state==a&&l.engine_snapshot_path.empty(),"host roundtrip");test(bytes(l.state.at("retained")[0].at("canonical"))==std::string("\0\x80\xff",3),"opaque bytes roundtrip");
 test(detail::cbor_extent(a)==Json::to_cbor(a).size(),"allocation-free CBOR extent"); Coordinator capped(root/"capped",4096);refuses([&]{(void)capped.transaction(a,4096);});refuses([&]{(void)capped.transaction(a,4095);});auto engine_failure=c.transaction(state(2));engine_failure.prepare_storage();engine_failure.abort("injected engine write failure");test(c.poll().failed&&!c.poll().in_flight,"engine abort clears in-flight");test(Coordinator::load(root).generation==l.generation,"engine failure preserves prior generation");auto thread_failure=c.transaction(state(2));thread_failure.abort("injected writer thread creation failure");test(c.poll().failed&&!c.poll().in_flight,"thread failure clears in-flight"); auto p=c.transaction(state(2));p.prepare_storage();refuses([&]{p.publish();});p.abort("publish refused absent engine");test(c.poll().failed&&!c.poll().in_flight,"publish abort clears in-flight");auto previous=Coordinator::load(root);test(previous.generation==l.generation,"missing engine preserves prior generation");
 auto p2=c.transaction(state(3));p2.prepare_storage();{detail::Fd f(::open(p2.snapshot_path.c_str(),O_WRONLY|O_CREAT|O_EXCL,0600));require(f.n>=0,"fake engine open");const char b[]="opaque engine payload";detail::write_all(f.n,b,sizeof(b));detail::sync(f.n);}p2.publish();auto both=Coordinator::load(root);test(both.state==state(3)&&both.engine_snapshot_path==p2.snapshot_path,"paired generation commit");
 // A different maintained workflow uses the same transport with its own schema.
 // Neither a resident study nor another controller may decode it accidentally.
 auto prefix_state=a;prefix_state["format"]="native-prefix-checkpoint-1";
 Coordinator prefix(root/"prefix",0,"native-prefix-checkpoint-1");
 test(prefix.save_host(prefix_state),"prefix host submission");prefix.finish();
 test(prefix.poll().committed&&Coordinator::load(root/"prefix",0,"native-prefix-checkpoint-1").state==prefix_state,"prefix state roundtrip");
 refuses([&]{(void)Coordinator::load(root/"prefix");});
 refuses([&]{(void)Coordinator::load(root/"prefix",0,"another-controller-1");});
 refuses([&]{(void)prefix.save_host(a);});
 refuses([&]{Coordinator empty_format(root/"empty-format",0,"");});
 test(Coordinator::load(root/"prefix",0,"native-prefix-checkpoint-1").state==prefix_state,"wrong schema preserves saved prefix state");
 const auto committed_manifest=detail::read_manifest(root/"current.json");auto bytes_path=root/both.generation/"host.cbor";{detail::Fd f(::open(bytes_path.c_str(),O_RDWR));require(f.n>=0,"corrupt test open");unsigned char x=0;require(::pread(f.n,&x,1,20)==1,"corrupt read");x^=1;require(::pwrite(f.n,&x,1,20)==1,"corrupt write");}refuses([&]{(void)Coordinator::load(root);});
 test(c.save_host(a),"recovery host submission");c.finish();auto good=Coordinator::load(root);test(good.state==a,"new generation after corruption");refuses([&]{(void)Coordinator::load(root,1);});
 auto bad_manifest=detail::read_manifest(root/"current.json");auto saved_manifest=bad_manifest;bad_manifest["generation"]="../escape";detail::atomic_manifest(root,bad_manifest,"escape-test");refuses([&]{(void)Coordinator::load(root);});detail::atomic_manifest(root,saved_manifest,"restore-test");bad_manifest=saved_manifest;bad_manifest["host_payload_bytes"]=std::uint64_t(0);detail::atomic_manifest(root,bad_manifest,"extent-test");refuses([&]{(void)Coordinator::load(root);});detail::atomic_manifest(root,saved_manifest,"restore-extent");
 auto final=Coordinator::load(root);auto file=root/final.generation/"host.cbor";require(::truncate(file.c_str(),17)==0,"truncate test");refuses([&]{(void)Coordinator::load(root);});
 refuses([&]{Coordinator relative("relative");});refuses([&]{(void)bytes(Json("not binary"));});refuses([&]{auto invalid=a;invalid["format"]="other";(void)c.transaction(invalid);});
 fs::path fail_root=root/"blocked";{std::ofstream out(fail_root);out<<"not a directory";}Coordinator failed(fail_root);test(failed.save_host(a),"failure submit");failed.finish();test(failed.poll().failed&&!failed.poll().committed,"background failure reporting");test(!fs::exists(fail_root/"current.json"),"failed write not published");
 std::cout<<Json{{"format","resident-study-checkpoint-CPU-checks-1"},{"checks",checks},{"errors",0},{"GPU_operations",0},{"model_predictions",0},{"scope","CBOR opaque payload, paired durable publication, corruption/truncation/path/budget refusals, background failure"}}.dump()<<'\n';return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
