#include "class_rank_regional_model_export.hpp"
#include "class_io.hpp"
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <cerrno>
#include <limits>
namespace rank_regional_model_export {namespace {
namespace fs=std::filesystem;using J=dpnative::json;using Node=collect::dl::Node;using Term=collect::dl::Term;
void need(bool b,const char*s){if(!b)throw std::runtime_error(s);}bool sha(const std::string&s){return s.size()==64&&s.find_first_not_of("0123456789abcdef")==std::string::npos;}
U add(U a,U b){need(a<=UINT64_MAX-b,"runtime byte count overflow");return a+b;}
void fixed(std::string&s,U v,unsigned n){for(unsigned i=0;i<n;++i)s+=char(v>>(8*i));}
void var(std::string&s,U x){do{auto b=std::uint8_t(x&127);x>>=7;s+=char(b|(x?128:0));}while(x);}
std::string unhex(const std::string&h){need(sha(h),"runtime SHA invalid");std::string s;for(unsigned k=0;k<64;k+=2){auto d=[](char c){return c<='9'?c-'0':c-'a'+10;};s+=char(d(h[k])*16+d(h[k+1]));}return s;}
std::string hex(const std::string&s){constexpr char h[]="0123456789abcdef";std::string r;for(unsigned char c:s){r+=h[c>>4];r+=h[c&15];}return r;}
struct Cursor{const std::string&s;std::size_t at=0;U word(unsigned n){need(at<=s.size()&&n<=s.size()-at,"runtime truncated word");U x=0;for(unsigned i=0;i<n;++i)x|=U(std::uint8_t(s[at++]))<<(8*i);return x;}U variable(){U x=0;for(unsigned k=0;k<10;++k){auto b=word(1);need(k!=9||b<=1,"runtime varint overflow");x|=(b&127)<<(7*k);if(!(b&128)){need(!k||(b&127),"runtime noncanonical varint");return x;}}throw std::runtime_error("runtime varint overflow");}std::string bytes(std::size_t n){need(at<=s.size()&&n<=s.size()-at,"runtime truncated bytes");auto r=s.substr(at,n);at+=n;return r;}};
void shape(const Model&m){need(sha(m.source_sha256)&&sha(m.rank_sha256)&&m.rank_sha256==rank_digest(m.rank_cut_bits),"runtime source/rank words differ");need(!m.nodes.empty()&&m.root==m.nodes.size()-1,"runtime designated collected root invalid");for(const auto&col:m.rank_cut_bits){need(col.size()<=0x1000000u,"runtime rank precision limit");U prior=0;bool first=true;for(auto w:col){need((w&0x7fffffffu)<0x7f800000u&&w!=0x80000000u,"runtime rank cut word invalid");U ordered=(w&0x80000000u)?U(~w):U(w^0x80000000u);need(first||prior<ordered,"runtime rank cuts not sorted unique");first=false;prior=ordered;}}for(unsigned k=0;k<10;++k)need(m.scope.lo[k]>=0&&m.scope.hi[k]>=m.scope.lo[k]&&U(m.scope.hi[k])<=m.rank_cut_bits[k].size(),"runtime regional rank bounds invalid");need(!(m.scope.allowed>>44)&&(m.scope.allowed&15)&&(m.scope.allowed>>4),"runtime regional category mask invalid");for(U i=0;i<m.terms.size();++i){const auto&t=m.terms[i];need(t.id==i&&t.feature>=0&&t.feature<54&&(t.weight_bits&0x7f800000u)!=0x7f800000u,"runtime term schema invalid");}for(U i=0;i<m.nodes.size();++i){const auto&n=m.nodes[i];need(n.id==i,"runtime dense node ID differs");if(n.kind==2){need(n.label>=0&&n.label<7&&n.left==arena::none&&n.right==arena::none&&!n.first_term&&!n.term_count&&n.feature==-1&&!n.cut_bits&&!n.threshold_bits,"runtime leaf unused words noncanonical");continue;}need(n.label==-1&&n.left<i&&n.right<i,"runtime cyclic/forward child reference");if(n.kind==0)need(n.feature>=0&&n.feature<54&&(n.cut_bits&0x7f800000u)!=0x7f800000u&&!n.first_term&&!n.term_count&&!n.threshold_bits,"runtime axis schema invalid");else need(n.kind==1&&n.feature==-1&&!n.cut_bits&&n.term_count>0&&n.first_term<=m.terms.size()&&n.term_count<=m.terms.size()-n.first_term&&(n.threshold_bits&0x7ff0000000000000ull)!=0x7ff0000000000000ull,"runtime plane schema invalid");}}
struct Encoded{std::string bytes;U header=0,ranks=0,nodes=0,terms=0;};
Encoded packing(const Model&m){shape(m);Encoded e;auto&s=e.bytes;s="CLSRMDL1";s+=char(1); // fixed forest_valid_v1/source-threshold-rank/RN separate-ops regional schema
s+=unhex(m.source_sha256);s+=unhex(m.rank_sha256);for(unsigned k=0;k<10;++k){var(s,U(m.scope.lo[k]));var(s,U(m.scope.hi[k]));}fixed(s,m.scope.allowed,6);var(s,m.root);var(s,m.nodes.size());var(s,m.terms.size());e.header=s.size();
for(const auto&col:m.rank_cut_bits){var(s,col.size());for(auto w:col)fixed(s,w,4);}e.ranks=s.size()-e.header;
for(const auto&n:m.nodes){if(n.kind==2){s+=char(n.label);continue;}s+=char(n.kind==0?7:8);var(s,n.id-n.left);var(s,n.id-n.right);if(n.kind==0){s+=char(n.feature);fixed(s,n.cut_bits,4);}else{var(s,n.first_term);var(s,n.term_count);fixed(s,n.threshold_bits,8);}}e.nodes=s.size()-e.header-e.ranks;
for(const auto&t:m.terms){s+=char(t.feature);fixed(s,t.weight_bits,4);}e.terms=s.size()-e.header-e.ranks-e.nodes;s+=unhex(dpnative::sha256(s));return e;}
J box(const tasks::Box&b){return {{"lo",b.lo},{"hi",b.hi},{"allowed",b.allowed}};}
void durable(const fs::path&p,const std::string&s){auto temp=p;temp+=".pending";int fd=::open(temp.c_str(),O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC,0600);need(fd>=0,"runtime output open failed");try{std::size_t at=0;while(at<s.size()){auto n=::write(fd,s.data()+at,s.size()-at);if(n<0&&errno==EINTR)continue;need(n>0,"runtime output write failed");at+=std::size_t(n);}need(!::fsync(fd),"runtime output fsync failed");need(!::close(fd),"runtime output close failed");fd=-1;need(!::rename(temp.c_str(),p.c_str()),"runtime output rename failed");int d=::open(p.parent_path().c_str(),O_RDONLY|O_DIRECTORY|O_CLOEXEC);need(d>=0,"runtime directory open failed");int a=::fsync(d),b=::close(d);need(!a&&!b,"runtime directory sync failed");}catch(...){if(fd>=0)::close(fd);throw;}}
bool beneath(const fs::path&p,const fs::path&root){auto a=fs::absolute(p).lexically_normal(),b=fs::absolute(root).lexically_normal();auto i=a.begin(),j=b.begin();for(;j!=b.end();++j,++i)if(i==a.end()||*i!=*j)return false;return true;}
}
std::string rank_digest(const RankWords&cuts){std::string raw;for(const auto&c:cuts){need(c.size()<=UINT32_MAX,"rank column count overflow");fixed(raw,c.size(),4);for(auto x:c)fixed(raw,x,4);}return dpnative::sha256(raw);}
std::string encode(const Model&m){return packing(m).bytes;}
Model decode(const std::string&raw){need(raw.size()>=32,"runtime model truncated");const auto content=raw.substr(0,raw.size()-32);need(hex(raw.substr(raw.size()-32))==dpnative::sha256(content),"runtime model checksum differs");Cursor c{content};need(c.bytes(8)=="CLSRMDL1"&&c.word(1)==1,"runtime format/scope schema invalid");Model m;m.source_sha256=hex(c.bytes(32));m.rank_sha256=hex(c.bytes(32));for(unsigned k=0;k<10;++k){auto lo=c.variable(),hi=c.variable();need(lo<=INT32_MAX&&hi<=INT32_MAX,"runtime rank endpoint overflow");m.scope.lo[k]=std::int32_t(lo);m.scope.hi[k]=std::int32_t(hi);}m.scope.allowed=c.word(6);m.root=c.variable();auto nn=c.variable(),nt=c.variable();need(nn<=content.size()-c.at&&nt<=(content.size()-c.at)/5,"runtime counts exceed file");for(auto&col:m.rank_cut_bits){auto n=c.variable();need(n<=(content.size()-c.at)/4&&n<=UINT32_MAX,"runtime rank table count exceeds file");col.reserve(n);for(U i=0;i<n;++i)col.push_back(std::uint32_t(c.word(4)));}m.nodes.reserve(nn);for(U i=0;i<nn;++i){Node n;n.id=i;auto tag=c.word(1);if(tag<=6)n.label=int(tag);else{need(tag==7||tag==8,"runtime node tag invalid");auto l=c.variable(),r=c.variable();need(l>0&&r>0&&l<=i&&r<=i,"runtime child delta invalid");n.left=i-l;n.right=i-r;n.label=-1;n.kind=tag==7?0:1;if(n.kind==0){n.feature=int(c.word(1));n.cut_bits=std::uint32_t(c.word(4));}else{n.first_term=c.variable();auto count=c.variable();need(count<=UINT32_MAX,"runtime term count overflow");n.term_count=std::uint32_t(count);n.threshold_bits=c.word(8);}}m.nodes.push_back(n);}m.terms.reserve(nt);for(U i=0;i<nt;++i)m.terms.push_back({i,std::int32_t(c.word(1)),std::uint32_t(c.word(4))});need(c.at==content.size(),"runtime trailing bytes");shape(m);need(encode(m)==raw,"runtime encoding is not canonical");return m;}
Model read_model(const fs::path&p,const std::string&expected,U maxbytes){need(sha(expected)&&fs::is_regular_file(p)&&!fs::is_symlink(p)&&fs::file_size(p)<=maxbytes,"runtime file identity/resource invalid");auto raw=dpnative::read_text(p);need(dpnative::sha256(raw)==expected,"runtime expected digest differs");return decode(raw);}
Usage directory_usage(const fs::path&dir,const fs::path&excluded){need(fs::is_directory(dir),"usage directory missing");Usage u;for(fs::recursive_directory_iterator it(dir),end;it!=end;++it){const auto p=it->path();if(!excluded.empty()&&beneath(p,excluded)){if(it->is_directory())it.disable_recursion_pending();continue;}need(!it->is_symlink(),"usage refuses symlink accounting");if(it->is_regular_file()){struct stat s{};need(!::stat(p.c_str(),&s)&&s.st_size>=0&&s.st_blocks>=0,"usage stat failed");u.files=add(u.files,1);u.logical_bytes=add(u.logical_bytes,U(s.st_size));need(U(s.st_blocks)<=UINT64_MAX/512,"usage allocation overflow");u.allocated_bytes=add(u.allocated_bytes,U(s.st_blocks)*512);}}return u;}
Result export_model(fs::path runtime,fs::path audit,Request request,Admission admit,Options options,const Stop&stop,int device){Result out;need(bool(admit)&&!request.binding.empty()&&sha(request.source_sha256)&&sha(request.rank_sha256)&&sha(request.graph_checkpoint_sha256)&&sha(request.current_policy_sha256)&&sha(request.root_proof_sha256),"regional export identity/admission missing");need(!fs::exists(runtime)&&!fs::exists(audit)&&!beneath(runtime,audit)&&!beneath(audit,runtime),"runtime/audit outputs must be fresh disjoint directories");need(request.resolved_root.id==0&&request.resolved_root.parent==arena::none&&request.resolved_root.status==tasks::Status::resolved&&request.resolved_root.module.id<request.graph.nodes.size()&&request.resolved_root.certificate!=arena::none,"regional export root unresolved");need(request.graph.prefix.nodes==request.graph.nodes.size()&&request.graph.prefix.terms==request.graph.terms.size()&&request.graph.modules.size()==request.graph.nodes.size()&&request.graph.modules[request.resolved_root.module.id]==request.resolved_root.module&&request.rank_sha256==rank_digest(request.rank_cut_bits),"regional export metadata mismatch");need(request.scope.lo==request.resolved_root.box.lo&&request.scope.hi==request.resolved_root.box.hi&&request.scope.allowed==request.resolved_root.box.allowed,"regional export scope differs from root contract");need(admit(request),"regional export current source contract rejected");if(stop&&stop()){out.reason="cancelled_before_runtime_collection";return out;}
collect::Input input{request.graph.nodes,request.graph.terms,{request.resolved_root.module.id},request.binding};auto collected=collect::collect(std::move(input),options.collector,stop,device);out.CUDA_executed=collected.CUDA_executed;if(!collected.complete){out.reason=collected.reason;return out;}need(collected.CUDA_executed&&collected.structural_verified&&collected.binding==request.binding&&collected.roots.size()==1&&collected.roots[0]<collected.nodes.size(),"regional collection result invalid");Model model{request.source_sha256,request.rank_sha256,request.scope,request.rank_cut_bits,std::move(collected.nodes),std::move(collected.terms),collected.roots[0]};auto encoded=packing(model);need(encoded.bytes.size()<=options.maximum_runtime_bytes,"runtime model storage budget exhausted");auto decoded=decode(encoded.bytes);need(decoded.nodes==model.nodes&&decoded.terms==model.terms&&decoded.root==model.root&&decoded.rank_cut_bits==model.rank_cut_bits&&decoded.scope.lo==model.scope.lo&&decoded.scope.hi==model.scope.hi&&decoded.scope.allowed==model.scope.allowed,"runtime exact roundtrip differs");if(stop&&stop()){out.reason="cancelled_before_runtime_publication";return out;}need(admit(request),"regional source context changed before publication");
need(fs::create_directories(runtime)&&fs::create_directories(audit),"regional output directory creation failed");J evidence={{"format","regional-runtime-export-audit-1"},{"whole_source_conversion_complete",false},{"scope","regional"},{"scope_box",box(request.scope)},{"source_sha256",request.source_sha256},{"rank_sha256",request.rank_sha256},{"current_policy_sha256",request.current_policy_sha256},{"graph_checkpoint_sha256",request.graph_checkpoint_sha256},{"root_proof_sha256",request.root_proof_sha256},{"root_certificate_id",request.resolved_root.certificate},{"original_root_module_id",request.resolved_root.module.id},{"collector_input_sha256",collected.input_sha256},{"collector_output_sha256",collected.output_sha256},{"collector_structural_verified",true},{"model_sha256",dpnative::sha256(encoded.bytes)},{"runtime_model_bytes",encoded.bytes.size()},{"header_bytes",encoded.header},{"rank_bytes",encoded.ranks},{"node_bytes",encoded.nodes},{"term_bytes",encoded.terms},{"checksum_bytes",32},{"nodes",model.nodes.size()},{"terms",model.terms.size()},{"root",model.root},{"runtime_requires_proof_or_mapping_tables",false},{"runtime_requires_source_ensemble",false}};
// Maps are construction evidence only; never copied into runtime_directory.
std::string maps="CLSRMAP1";fixed(maps,collected.node_map.size(),8);fixed(maps,collected.term_map.size(),8);for(U x:collected.node_map)fixed(maps,x,8);for(U x:collected.term_map)fixed(maps,x,8);durable(audit/"collection-maps.bin",maps);auto ev=evidence.dump(2)+"\n";durable(audit/"export-audit.json",ev);need(admit(request),"regional source context changed after audit publication");durable(runtime/"model.bin",encoded.bytes);auto read=read_model(runtime/"model.bin",evidence.at("model_sha256"),options.maximum_runtime_bytes);need(read.nodes==model.nodes&&read.terms==model.terms,"runtime disk readback differs");need(admit(request),"regional source context changed after runtime publication");out.complete=true;out.reason="designated_regional_root_exported_without_construction_tables";out.model_sha256=evidence.at("model_sha256");out.audit_sha256=dpnative::sha256(ev);out.runtime_model_bytes=directory_usage(runtime).logical_bytes;out.construction_audit_bytes=directory_usage(audit).logical_bytes;out.nodes=model.nodes.size();out.terms=model.terms.size();out.root=model.root;out.header_bytes=encoded.header;out.rank_bytes=encoded.ranks;out.node_bytes=encoded.nodes;out.term_bytes=encoded.terms;out.checksum_bytes=32;need(out.runtime_model_bytes==encoded.bytes.size(),"unexpected runtime files");return out;
}
}
