// Maintained adjacent-predicate simplifier; all persisted-model inference
// and output-format validation consume the shared Runtime automatically.
#include "class_dag_storage.cuh"
#include <chrono>
using J=nlohmann::json;
void require(bool b,const std::string&m){if(!b)throw std::runtime_error(m);}
void Cpath(const fs::path&p){require(p.is_absolute()&&p.string().find('\0')==std::string::npos,"absolute dataset or output path required");(void)fs::weakly_canonical(p);}
#include "class_study_simplify_algorithms.cuh"
Dag fixture_dag(const std::vector<Node>&nodes,u32 root){Dag d;d.nodes=Dev<Node>(nodes.size());d.nodes.put(nodes);d.root=root;d.built=nodes.size();return d;}
J fixture(){
 const u32 F=2,K=2;const std::string identity(64,'0');const std::vector<u32>words={0xff7fffffu,0xbf800000u,0x80000001u,0x80000000u,0u,1u,0x3f800000u,0x7f7fffffu,0x7fc00001u,0xffc12345u};const u32 rows=words.size()*words.size();Dev<u32>w(words.size());w.put(words);Dev<float>x(u64(rows)*F);fixture_inputs<<<blocks(rows),256>>>(x.p,rows,F,w.p,u32(words.size()));done();
 struct Case{std::string name;std::vector<Node>nodes;u32 root,expected_nodes;bool expect_bypass;};const Node a{0,0,0,1},gate{-2,0xff7fffffu,0,1};
 std::vector<Case>cases={
  {"left_complete_chain",{{-1,0,0,0},{-1,1,0,0},a,{0,0,2,1},{0,0,3,1}},4,3,true},
  {"right_complete_chain",{{-1,0,0,0},{-1,1,0,0},a,{0,0,0,2},{0,0,0,3}},4,3,true},
  {"shared_child_different_parent",{{-1,0,0,0},{-1,1,0,0},a,{0,0,2,1},{1,0,3,2}},4,3,true},
  {"raw_signed_zero_cut_differs",{{-1,0,0,0},{-1,1,0,0},a,{0,0x80000000u,2,1}},3,4,false},
  {"NaN_default_direction_differs",{{-1,0,0,0},{-1,1,0,0},a,{-2,0,2,1}},3,4,false},
  {"feature_identity_differs",{{-1,0,0,0},{-1,1,0,0},a,{1,0,2,1}},3,4,false},
  {"identical_negative_cut_and_NaN_gate",{{-1,0,0,0},{-1,1,0,0},gate,{-2,0xff7fffffu,2,1}},3,3,true},
  {"collapse_exposes_next_prefix",{{-1,0,0,0},{-1,1,0,0},a,a,{1,0,2,3},{0,0,4,1}},5,3,true},
  {"root_leaf_and_unreachable_nodes",{{-1,0,0,0},{-1,1,0,0},a},0,1,false},
 };
 J receipts=J::array();for(const auto&c:cases){auto original=fixture_dag(c.nodes,c.root);auto bytes=encode(original,F,K,identity);auto decoded=decode(bytes,F,K,identity);auto result=simplify(decoded,K,4);require(result.fixed,"fixture fixed point not reached");auto serialized=encode(result.dag,F,K,identity);auto loaded=decode(serialized,F,K,identity);require(loaded.nodes.n==c.expected_nodes&&encode(decoded,F,K,identity)==bytes,"fixture size/input immutability differs");Dev<u32>old(rows),fresh(rows),bad(1),errors(1);bad.zero();errors.zero();predict_fixture(decoded,x.p,rows,F,K,old.p);predict_fixture(loaded,x.p,rows,F,K,fresh.p);compare_labels<<<blocks(rows),256>>>(old.p,fresh.p,rows,errors.p);done();require(!bad.at(0)&&!errors.at(0),"fixture original/simplified output differs");u64 rewrites=0;for(const auto&p:result.passes)rewrites+=p.at("rewritten_parent_edges").get<u64>();require(bool(rewrites)==c.expect_bypass,"fixture expected bypass applicability differs");receipts.push_back({{"case",c.name},{"rows",rows},{"raw_nodes",c.nodes.size()},{"output_nodes",loaded.nodes.n},{"class_mismatches",0},{"input_words_unchanged",true},{"fixed_point_reached",result.fixed},{"passes",result.passes}});}
 auto exposed=fixture_dag(cases[7].nodes,cases[7].root);auto budget=simplify(exposed,K,1);require(!budget.fixed&&budget.dag.nodes.n==4,"bounded exact nonfixed-point case differs");Dev<u32>old(rows),fresh(rows),bad(1),errors(1);bad.zero();errors.zero();predict_fixture(exposed,x.p,rows,F,K,old.p);predict_fixture(budget.dag,x.p,rows,F,K,fresh.p);compare_labels<<<blocks(rows),256>>>(old.p,fresh.p,rows,errors.p);done();require(!bad.at(0)&&!errors.at(0),"bounded nonfixed-point output differs");
 u32 rejected=0;for(auto invalid:std::vector<std::vector<Node>>{{{-1,0,0,0},{-1,1,0,0},{0,0,2,1}},{{-1,0,0,0},{-1,1,0,0},{0,0,0,3}},{{-1,0,0,0},{-1,2,0,0},{0,0,0,1}},{{-1,0,0,0},{-1,1,0,0},{INT32_MIN,0,0,1}},{{-1,0,0,0},{-1,1,0,0},{0,0x7fc00000u,0,1}}}){auto raw=fixture_dag(invalid,2);bool refused=false;try{(void)decode(encode(raw,F,K,identity),F,K,identity);}catch(const std::exception&){refused=true;}require(refused,"invalid serialized graph accepted");++rejected;}
 return {{"format","adjacent-predicate-simplifier-fixture-1"},{"complete",true},{"CUDA_executed",true},{"CPU_predictions",false},{"TEST_read",false},{"domain","finite FP32 plus NaN"},{"raw_feature_word_cases",words},{"cases",receipts},{"invalid_graphs_rejected",rejected},{"bounded_nonfixed_point_case",{{"exact",true},{"fixed_point_reached",false},{"class_mismatches",0},{"passes",budget.passes}}},{"consumer_peak_owned_CUDA_bytes_excluding_shared_Runtime_native_and_Thrust",peak_owned}};
}
J execute(const fs::path&planpath,const std::string&pin,const fs::path&out,const fs::path&exe){Cpath(planpath);auto pb=read_text(planpath);require(sha256(pb)==pin,"plan pin differs");auto p=J::parse(pb);require(p.at("format")=="adjacent-predicate-simplification-plan-1"&&p.at("TEST_read")==false&&p.at("training_performed")==false&&p.at("selection_performed")==false,"plan protocol");require(sha256(read_text(exe))==p.at("executable_sha256").get<std::string>(),"executable pin differs");u32 F=p.at("features"),K=p.at("classes"),budget=p.at("max_passes"),max_nodes=p.at("max_nodes");require(F>=1&&F<=1000000&&K>=2&&K<=1024&&budget>=1&&budget<=16&&max_nodes>0&&max_nodes<=16777216,"plan shape/capacity");fs::path input=p.at("canonical_runtime_path").get<std::string>(),source=p.at("source_path").get<std::string>();Cpath(input);Cpath(source);auto bytes=read_text(input),sourcebytes=read_text(source);std::string sourcepin=p.at("source_sha256");require(sha256(bytes)==p.at("canonical_runtime_sha256").get<std::string>()&&sha256(sourcebytes)==sourcepin,"source/runtime pins differ");require(bytes.size()<=64+u64(max_nodes)*16,"planned runtime byte limit exceeded");auto original=decode(bytes,F,K,sourcepin);require(original.nodes.n<=max_nodes,"planned node limit exceeded");clean_output(out);auto begin=std::chrono::steady_clock::now();auto candidate=simplify(original,K,budget);auto encoded=encode(candidate.dag,F,K,sourcepin);atomic_text(out/"model.clsgdag",encoded);auto readback=read_text(out/"model.clsgdag");require(readback==encoded,"canonical readback differs");auto validated=decode(readback,F,K,sourcepin);auto shared=class_runtime::Runtime::load(readback,sha256(readback),sourcepin);auto packed=shared->metadata().compact_resident?shared->compact_bytes():std::string();if(!packed.empty())atomic_text(out/"model.clsg64",packed);require(encode(original,F,K,sourcepin)==bytes&&sha256(read_text(input))==p.at("canonical_runtime_sha256").get<std::string>()&&sha256(read_text(source))==sourcepin&&sha256(read_text(exe))==p.at("executable_sha256").get<std::string>()&&sha256(read_text(planpath))==pin,"final immutable input/pin audit differs");
 J proof={{"exact_support",true},{"domain","all finite FP32 plus NaN"},{"predicate_equality","exact signed feature word including NaN default direction AND raw FP32 cut bits"},{"edge_rule","If parent predicate P takes branch b and its child Q has identical predicate words, Q takes b for the same input. Replace only that parent edge by Q.branch[b], repeating over the complete older-ID identical prefix."},{"shared_DAG_rule","Every pass reads an immutable node snapshot and writes separate parent copies. Shared child semantics are preserved by older-ID induction; no shared source node is edited in place."},{"collapse_rule","Resolve older children first. Equal-child parents are replaced by that child; exact four-word structural duplicates share the existing representative."},{"collection_rule","Descending serial live marking visits parents before their older children; existing GPU exclusive_scan/collect_nodes only renumbers root-reachable representatives."},{"numeric_implications_used",false},{"CPU_numerical_predicate_computation",false},{"Lean_prefix_law_receipt",p.at("Lean_prefix_law_receipt")},{"whole_shared_DAG_pass_machine_checked",false},{"outer_pass_budget",budget},{"fixed_point_reached",candidate.fixed},{"exact_if_outer_budget_exhausted",true}};atomic_json(out/"support-proof.json",proof);
 J result={{"format","adjacent-predicate-simplification-result-1"},{"complete",true},{"CUDA_executed",true},{"CPU_predictions",false},{"TEST_read",false},{"training_performed",false},{"selection_performed",false},{"case_id",p.at("case_id")},{"features",F},{"classes",K},{"source_path",source.string()},{"source_sha256",sourcepin},{"input_canonical_runtime_path",input.string()},{"input_canonical_runtime_sha256",sha256(bytes)},{"output_canonical_runtime_path",(out/"model.clsgdag").string()},{"output_canonical_runtime_sha256",sha256(encoded)},{"canonical_format","CLSGDAG1"},{"source_binding_preserved",true},{"input_file_and_GPU_words_unchanged",true},{"raw_nodes",original.nodes.n},{"reachable_output_nodes",validated.nodes.n},{"original_root",original.root},{"output_root",validated.root},{"runtime_bytes_before",bytes.size()},{"runtime_bytes_after",encoded.size()},{"max_passes",budget},{"passes_completed",candidate.passes.size()},{"fixed_point_reached",candidate.fixed},{"exact_support",true},{"support_proof_sha256",sha256(read_text(out/"support-proof.json"))},{"passes",candidate.passes},{"consumer_peak_owned_CUDA_bytes_excluding_shared_Runtime_native_and_Thrust",peak_owned},{"host_transform_seconds_including_canonical_encode_readback_validation",std::chrono::duration<double>(std::chrono::steady_clock::now()-begin).count()},{"transform_timings_rank_inference_speed",false},{"plan_sha256",pin},{"executable_sha256",p.at("executable_sha256").get<std::string>()},{"native_inference_qualification_pending",true},{"output_inference_module","native/class_runtime"},{"output_compact_runtime_available",!packed.empty()},{"output_compact_runtime_path",packed.empty()?J(nullptr):J((out/"model.clsg64").string())},{"output_compact_runtime_sha256",packed.empty()?J(nullptr):J(sha256(packed))},{"output_shared_retained_graph_device_bytes",shared->metadata().device_bytes},{"output_full_cross_layout_words_equal",shared->metadata().cross_layout_validated}};atomic_json(out/"result.json",result);atomic_json(out/"result-seal.json",{{"sealed",true},{"result_sha256",sha256(read_text(out/"result.json"))},{"plan_sha256",pin},{"executable_sha256",p.at("executable_sha256").get<std::string>()},{"source_sha256",sourcepin}});return result;
}
int main(int argc,char**argv){try{require((argc==3&&std::string(argv[1])=="fixture")||(argc==5&&std::string(argv[1])=="simplify"),"fixture OUT | simplify PLAN SHA OUT");fs::path out=fs::absolute(argv[argc-1]);Cpath(out);require(!fs::exists(out),"output exists");ck(cudaSetDevice(0),"device");J result;if(argc==3){clean_output(out);result=fixture();atomic_json(out/"result.json",result);}else result=execute(argv[2],argv[3],out,fs::canonical("/proc/self/exe"));std::cout<<result.dump(2)<<'\n';return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
