include_guard(GLOBAL)

option(GH_COMPILER_DIAGNOSTICS "Emit CUDA resource, inlining and spill diagnostics; retain normal optimization/arithmetic flags" OFF)
option(GH_COMPILER_TIME_TRACE "Emit one device compilation time trace per CUDA object" OFF)
option(GH_DEVICE_SANITIZE "Compile CUDA device memcheck instrumentation; run these binaries ONLY under Compute Sanitizer" OFF)

function(gh_configure_cuda_diagnostics)
  if(NOT (GH_COMPILER_DIAGNOSTICS OR GH_COMPILER_TIME_TRACE OR GH_DEVICE_SANITIZE))
    return()
  endif()
  if(NOT CMAKE_CUDA_COMPILER_ID STREQUAL "NVIDIA")
    message(FATAL_ERROR "Requested GH compiler diagnostics require the NVIDIA CUDA compiler")
  endif()
  execute_process(COMMAND "${CMAKE_CUDA_COMPILER}" --help
    RESULT_VARIABLE help_status OUTPUT_VARIABLE compiler_help ERROR_VARIABLE help_error)
  if(NOT help_status EQUAL 0)
    message(FATAL_ERROR "Cannot inspect CUDA compiler capabilities: ${help_error}")
  endif()
  if(GH_COMPILER_DIAGNOSTICS)
    foreach(flag IN ITEMS "--resource-usage" "--optimization-info")
      string(FIND "${compiler_help}" "${flag}" position)
      if(position EQUAL -1)
        message(FATAL_ERROR "Selected CUDA compiler does not advertise ${flag}")
      endif()
    endforeach()
    add_compile_options("$<$<COMPILE_LANGUAGE:CUDA>:--resource-usage;--optimization-info=inline;-Xptxas=--warn-on-spills,--warn-on-local-memory-usage>")
  endif()
  if(GH_COMPILER_TIME_TRACE)
    string(FIND "${compiler_help}" "--fdevice-time-trace" position)
    if(position EQUAL -1)
      message(FATAL_ERROR "Selected CUDA compiler does not support device compilation traces")
    endif()
    add_compile_options($<$<COMPILE_LANGUAGE:CUDA>:--fdevice-time-trace=->)
    message(WARNING "GH_COMPILER_TIME_TRACE: nvcc 13.4.59 was observed to change generated GPU instructions with --fdevice-time-trace. Use this as a separate compile-cost build, never as the runtime performance baseline")
  endif()
  if(GH_DEVICE_SANITIZE)
    string(FIND "${compiler_help}" "--fdevice-sanitize" position)
    if(position EQUAL -1)
      message(FATAL_ERROR "Selected CUDA compiler does not support --fdevice-sanitize=memcheck")
    endif()
    find_program(GH_COMPUTE_SANITIZER NAMES compute-sanitizer
      HINTS "${CUDAToolkit_BIN_DIR}" REQUIRED)
    set(GH_COMPUTE_SANITIZER "${GH_COMPUTE_SANITIZER}" CACHE FILEPATH "Compute Sanitizer for instrumented GPU tests")
    add_compile_options($<$<COMPILE_LANGUAGE:CUDA>:--fdevice-sanitize=memcheck>)
    message(WARNING "GH_DEVICE_SANITIZE: run generated CUDA binaries ONLY under compute-sanitizer --tool memcheck; ordinary execution is undefined and timings are diagnostic only")
  endif()
  message(STATUS "GH diagnostics: resources=${GH_COMPILER_DIAGNOSTICS}, time traces=${GH_COMPILER_TIME_TRACE}, device memcheck=${GH_DEVICE_SANITIZE}; existing optimization and arithmetic flags retained")
endfunction()

# The compiler-instrumented device runtime requires a memcheck collector.
function(gh_add_gpu_test)
  cmake_parse_arguments(ARG "" "NAME" "COMMAND" ${ARGN})
  if(GH_DEVICE_SANITIZE)
    if(NOT GH_COMPUTE_SANITIZER)
      find_program(GH_COMPUTE_SANITIZER NAMES compute-sanitizer
        HINTS "${CUDAToolkit_BIN_DIR}" REQUIRED)
    endif()
    list(POP_FRONT ARG_COMMAND test_executable)
    if(TARGET "${test_executable}")
      set(test_executable "$<TARGET_FILE:${test_executable}>")
    endif()
    add_test(NAME "${ARG_NAME}" COMMAND "${GH_COMPUTE_SANITIZER}" --tool memcheck
      --error-exitcode 99 "${test_executable}" ${ARG_COMMAND})
  else()
    add_test(NAME "${ARG_NAME}" COMMAND ${ARG_COMMAND})
  endif()
endfunction()
