#include "streaming_file_hash.hpp"
#pragma once
#include "class_rank_gpu_class_apply_receipt.hpp"
#include "class_rank_gpu_score_source_apply.hpp"
namespace source_apply_receipt {
using namespace apply_receipt;namespace source_apply=rank_gpu_score_source_apply;
inline J build(const fs::path&source){return apply_receipt::build(source);}
inline J describe(const source_apply::Result&r){J steps=J::array();for(const auto&s:r.steps)steps.push_back(J{{"source_tree",s.source_tree},{"channel",s.channel},{"class_prefix",s.class_prefix},{"complete",s.complete},{"reason",s.reason},{"operation_binding",s.operation_binding},{"tree_graph_digest",s.tree_graph_digest},{"before_graph_digest",s.before_graph_digest},{"after_graph_digest",s.after_graph_digest},{"tree_transport_rows",s.tree_transport_rows},{"tree_states",s.tree_counters.states},{"tree_state_hits",s.tree_counters.state_hits},{"tree_nodes",s.tree_counters.nodes},{"tree_arcs",s.tree_counters.arcs},{"tree_congruence_complete",s.tree_audit.complete},{"Add_pairs",s.add_counters.pairs},{"Add_pair_hits",s.add_counters.pair_hits},{"Add_open_hits",s.add_counters.open_hits},{"Add_nodes",s.add_counters.nodes},{"Add_arcs",s.add_counters.arcs},{"Add_terminal_additions",s.add_counters.terminal_additions},{"Add_congruence_complete",s.add_audit.complete},{"Add_audit_triples",s.add_audit.triples},{"Add_audit_transitions",s.add_audit.transitions},{"Add_audit_terminal_words",s.add_audit.terminal_word_checks},{"owned_device_peak_bytes",s.owned_device_peak_bytes}});return J{{"complete",r.complete},{"CUDA_executed",r.CUDA_executed},{"reason",r.reason},{"source_digest",r.source_digest},{"sequence_digest",r.sequence_digest},{"source_trees",r.source_trees},{"completed_trees",r.completed_trees},{"completed_class_prefixes",r.completed_class_prefixes},{"owned_device_peak_bytes",r.owned_device_peak_bytes},{"retained_graph_logical_bytes_highwater",r.retained_graph_logical_bytes_highwater},{"packing_audited_nodes",r.packing_audited_nodes},{"packing_audited_arcs",r.packing_audited_arcs},{"bias_transport_rows",r.bias_transport_rows},{"bias_audit_complete",r.bias_audit.complete},{"steps",std::move(steps)},{"per_graph_payloads_materialized_in_JSON",false}};}
}
