#include "class_rank_gpu_online_cache.hpp"
#include <cuda_runtime.h>
#include <algorithm>
#include <limits>
#include <stdexcept>
#include <utility>
namespace rank_gpu_online_cache { namespace {
using U=std::uint64_t;
struct CudaError:std::runtime_error{using std::runtime_error::runtime_error;};
void ck(cudaError_t e){if(e!=cudaSuccess)throw CudaError(cudaGetErrorString(e));}
void need(bool x,const char*s){if(!x)throw std::runtime_error(s);}
U slots(U n){U s=1;while(s<2*n)s*=2;return s;}
unsigned grid(U n){return static_cast<unsigned>(std::min<U>((n+255)/256,65535));}
template<class T>struct Buffer{T*p=nullptr;U n=0;Buffer()=default;~Buffer(){if(p)cudaFree(p);}Buffer(const Buffer&)=delete;void alloc(U k){if(p)return;n=k;if(k)ck(cudaMalloc(&p,k*sizeof(T)));}};
struct Control {U stage_nodes=0,stage_terms=0,undo_count=0;Work work{};unsigned bad=0;};
static_assert(sizeof(Control)<=256);
__device__ void bad(Control*c,unsigned x){atomicCAS(&c->bad,0u,x);}
__device__ bool finite32(std::uint32_t b){return (b&0x7f800000u)!=0x7f800000u;}
__device__ bool finite64(U b){return (b&0x7ff0000000000000ull)!=0x7ff0000000000000ull;}
__device__ bool addok(U a,U b,U&v){if(a>UINT64_MAX-b)return false;v=a+b;return true;}
__device__ bool node_shape(const dl::Node&n,U terms){
 if(n.kind==2)return n.label>=0&&n.label<7&&n.left==none&&n.right==none&&n.feature==-1&&!n.first_term&&!n.term_count&&!n.cut_bits&&!n.threshold_bits;
 if(n.label!=-1||n.left>=n.id||n.right>=n.id)return false;
 if(n.kind==0)return n.feature>=0&&n.feature<54&&finite32(n.cut_bits)&&!n.first_term&&!n.term_count&&!n.threshold_bits;
 return n.kind==1&&n.feature==-1&&!n.cut_bits&&finite64(n.threshold_bits)&&n.term_count&&n.first_term<=terms&&n.term_count<=terms-n.first_term;
}
__device__ void satadd(U a,unsigned af,U b,unsigned bf,U&out,unsigned&flag){flag=af||bf||a>UINT64_MAX-b;out=flag?UINT64_MAX:a+b;}
__device__ bool module_calc(const dl::Node&n,const Module&l,const Module&r,Module&m){m.id=n.id;if(n.kind==2){m.expanded_nodes=1;m.expanded_terms=0;m.height=0;m.nodes_saturated=m.terms_saturated=0;return true;}U a,b;unsigned af,bf;satadd(l.expanded_nodes,l.nodes_saturated,r.expanded_nodes,r.nodes_saturated,a,af);satadd(a,af,1,0,m.expanded_nodes,m.nodes_saturated);satadd(l.expanded_terms,l.terms_saturated,r.expanded_terms,r.terms_saturated,b,bf);satadd(b,bf,n.term_count,0,m.expanded_terms,m.terms_saturated);return addok(l.height>r.height?l.height:r.height,1,m.height);}

struct View {const dl::Node*oldn;const dl::Term*oldt;const Module*oldm;const dl::Node*newn;const dl::Term*newt;const Module*newm;U bn,bt;
 __device__ dl::Node node(U id)const{return id<bn?oldn[id]:newn[id-bn];}
 __device__ Module module(U id)const{return id<bn?oldm[id]:newm[id-bn];}
 __device__ dl::Term term(U id)const{return id<bt?oldt[id]:newt[id-bt];}
};
__device__ U mix(U h,U x){h^=x;h*=1099511628211ull;h^=h>>32;return h;}
__device__ U hashkey(const dl::Node&n,const dl::Term*t,unsigned bits){U h=1469598103934665603ull;h=mix(h,n.kind);h=mix(h,static_cast<std::uint32_t>(n.label));h=mix(h,static_cast<std::uint32_t>(n.feature));h=mix(h,n.cut_bits);h=mix(h,n.threshold_bits);h=mix(h,n.left);h=mix(h,n.right);h=mix(h,n.term_count);for(unsigned j=0;j<n.term_count;++j){h=mix(h,static_cast<std::uint32_t>(t[j].feature));h=mix(h,t[j].weight_bits);}return bits==64?h:bits? h&((1ull<<bits)-1):0;}
__device__ bool same(const dl::Node&a,const dl::Term*at,const dl::Node&b,const View&v){if(a.kind!=b.kind||a.label!=b.label||a.feature!=b.feature||a.cut_bits!=b.cut_bits||a.threshold_bits!=b.threshold_bits||a.left!=b.left||a.right!=b.right||a.term_count!=b.term_count)return false;for(unsigned j=0;j<a.term_count;++j){auto t=v.term(b.first_term+j);if(at[j].feature!=t.feature||at[j].weight_bits!=t.weight_bits)return false;}return true;}
__device__ U find(const dl::Node&n,const dl::Term*t,U h,const U*tab,U cap,const View&v,Control*c){for(U j=0;j<cap;++j){U k=(h+j)&(cap-1),id=tab[k];++c->work.hash_probes;if(id==none)return none;++c->work.exact_key_comparisons;if(same(n,t,v.node(id),v))return id;}bad(c,20);return none;}
__global__ void validate_seed(const dl::Node*n,U nn,const dl::Term*t,U nt,Control*c){for(U i=blockIdx.x*blockDim.x+threadIdx.x;i<nn;i+=gridDim.x*blockDim.x)if(n[i].id!=i||!node_shape(n[i],nt)||n[i].kind!=2&&n[i].left==n[i].right)bad(c,1);for(U i=blockIdx.x*blockDim.x+threadIdx.x;i<nt;i+=gridDim.x*blockDim.x)if(t[i].id!=i||t[i].feature<0||t[i].feature>=54||!finite32(t[i].weight_bits))bad(c,2);}
__global__ void seed_chunk(dl::Node*n,U nn,dl::Term*t,U nt,Module*m,U*tab,U cap,unsigned bits,U begin,U end,Control*c){if(threadIdx.x||blockIdx.x||c->bad)return;View v{n,t,m,nullptr,nullptr,nullptr,nn,nt};for(U i=begin;i<end;++i){auto x=n[i];if(x.kind==1){if(x.first_term!=c->stage_terms){bad(c,3);return;}c->stage_terms+=x.term_count;}auto h=hashkey(x,x.term_count?t+x.first_term:nullptr,bits);U found=find(x,x.term_count?t+x.first_term:nullptr,h,tab,cap,v,c);if(c->bad)return;if(found!=none){bad(c,4);return;}Module z,l{},r{};if(x.kind!=2){l=m[x.left];r=m[x.right];}if(!module_calc(x,l,r,z)){bad(c,5);return;}m[i]=z;for(U j=0;j<cap;++j){U k=(h+j)&(cap-1);if(tab[k]==none){tab[k]=i;break;}}c->stage_nodes=i+1;}}
__device__ bool refvalid(const Ref&r,U row,U base){return r.kind==1?r.id<base:r.kind==2&&r.id<row;}
__global__ void validate_request(const Draft*n,U nn,const dl::Term*t,U nt,U bn,Control*c){for(U i=blockIdx.x*blockDim.x+threadIdx.x;i<nt;i+=gridDim.x*blockDim.x)if(t[i].id!=i||t[i].feature<0||t[i].feature>=54||!finite32(t[i].weight_bits))bad(c,7);for(U i=blockIdx.x*blockDim.x+threadIdx.x;i<nn;i+=gridDim.x*blockDim.x){auto x=n[i];bool ok;if(x.kind==2)ok=x.label>=0&&x.label<7&&x.left.kind==0&&x.left.id==none&&x.right.kind==0&&x.right.id==none&&x.feature==-1&&!x.first_term&&!x.term_count&&!x.cut_bits&&!x.threshold_bits;else {ok=x.label==-1&&refvalid(x.left,i,bn)&&refvalid(x.right,i,bn);if(x.kind==0)ok=ok&&x.feature>=0&&x.feature<54&&finite32(x.cut_bits)&&!x.first_term&&!x.term_count&&!x.threshold_bits;else ok=ok&&x.kind==1&&x.feature==-1&&!x.cut_bits&&finite64(x.threshold_bits)&&x.term_count&&x.first_term<=nt&&x.term_count<=nt-x.first_term;}if(!ok)bad(c,6);}}
__device__ U resolve(const Ref&r,const Module*map){return r.kind==1?r.id:map[r.id].id;}
__device__ dl::Node candidate(const Draft&d,const Module*map){dl::Node x;x.kind=d.kind;x.label=d.label;x.feature=d.feature;x.cut_bits=d.cut_bits;x.threshold_bits=d.threshold_bits;x.term_count=d.term_count;if(d.kind!=2){x.left=resolve(d.left,map);x.right=resolve(d.right,map);}return x;}
__global__ void stage(const Draft*d,const dl::Term*t,Module*map,View v,dl::Node*nn,dl::Term*nt,Module*nm,const U*oldtab,U oldcap,U*newtab,U newcap,U maxn,U maxt,unsigned bits,U begin,U end,Control*c){if(threadIdx.x||blockIdx.x||c->bad)return;for(U i=begin;i<end;++i){auto x=candidate(d[i],map);if(x.kind!=2&&x.left==x.right){map[i]=v.module(x.left);++c->work.equal_child_eliminations;++c->work.rows;continue;}const dl::Term*ts=x.term_count?t+d[i].first_term:nullptr;auto h=hashkey(x,ts,bits);U id=find(x,ts,h,oldtab,oldcap,v,c);if(c->bad)return;if(id==none)id=find(x,ts,h,newtab,newcap,v,c);if(c->bad)return;if(id!=none){map[i]=v.module(id);++c->work.duplicate_hits;++c->work.rows;continue;}if(c->stage_nodes>=maxn||x.term_count>maxt-c->stage_terms){bad(c,100);return;}x.id=v.bn+c->stage_nodes;if(x.kind==1)x.first_term=v.bt+c->stage_terms;Module z,l{},r{};if(x.kind!=2){l=v.module(x.left);r=v.module(x.right);}if(!module_calc(x,l,r,z)){bad(c,8);return;}for(unsigned j=0;j<x.term_count;++j){auto a=ts[j];a.id=v.bt+c->stage_terms+j;nt[c->stage_terms+j]=a;}nn[c->stage_nodes]=x;nm[c->stage_nodes]=z;map[i]=z;for(U j=0;j<newcap;++j){U k=(h+j)&(newcap-1);if(newtab[k]==none){newtab[k]=x.id;break;}}++c->stage_nodes;c->stage_terms+=x.term_count;++c->work.rows;}}
__global__ void audit(const Draft*d,U nr,const dl::Term*t,const Module*map,View v,Control*c){if(c->bad)return;for(U i=blockIdx.x*blockDim.x+threadIdx.x;i<nr;i+=gridDim.x*blockDim.x){auto x=candidate(d[i],map);auto got=map[i];if(got.id>=v.bn+c->stage_nodes){bad(c,9);continue;}auto want=v.module(got.id);if(got.expanded_nodes!=want.expanded_nodes||got.expanded_terms!=want.expanded_terms||got.height!=want.height||got.nodes_saturated!=want.nodes_saturated||got.terms_saturated!=want.terms_saturated){bad(c,10);continue;}if(x.kind!=2&&x.left==x.right){if(got.id!=x.left)bad(c,11);}else if(!same(x,x.term_count?t+d[i].first_term:nullptr,v.node(got.id),v))bad(c,12);}
 for(U j=blockIdx.x*blockDim.x+threadIdx.x;j<c->stage_nodes;j+=gridDim.x*blockDim.x){auto x=v.node(v.bn+j);if(x.id!=v.bn+j||!node_shape(x,v.bt+c->stage_terms)||x.kind!=2&&x.left==x.right){bad(c,13);continue;}Module z,l{},r{};if(x.kind!=2){l=v.module(x.left);r=v.module(x.right);}auto m=v.module(x.id);if(!module_calc(x,l,r,z)||m.id!=z.id||m.expanded_nodes!=z.expanded_nodes||m.expanded_terms!=z.expanded_terms||m.height!=z.height||m.nodes_saturated!=z.nodes_saturated||m.terms_saturated!=z.terms_saturated)bad(c,14);}}
__global__ void install(const dl::Node*n,const dl::Term*t,U begin,U end,U*tab,U cap,unsigned bits,U*undo,Control*c){if(threadIdx.x||blockIdx.x||c->bad)return;for(U i=begin;i<end;++i){auto x=n[i];auto h=hashkey(x,x.term_count?t+x.first_term:nullptr,bits);bool done=false;for(U j=0;j<cap;++j){U k=(h+j)&(cap-1);if(tab[k]==none){undo[c->undo_count++]=k;tab[k]=i;done=true;break;}}if(!done){bad(c,15);return;}}}
__global__ void rollback(U*tab,const U*undo,const Control*c){for(U i=blockIdx.x*blockDim.x+threadIdx.x;i<c->undo_count;i+=gridDim.x*blockDim.x)tab[undo[i]]=none;}
struct Busy{bool&b;explicit Busy(bool&x):b(x){need(!b,"online arena reentrant use");b=true;}~Busy(){b=false;}};
}
struct Arena::Impl {
 Seed seed;Options opts;int device;Prefix head;bool ready=false,failed=false,busy=false;std::optional<Extension>last;
 Buffer<dl::Node> nodes,staged_nodes;Buffer<dl::Term>terms,request_terms,staged_terms;Buffer<Module>modules,mapping,staged_modules;Buffer<Draft>draft;Buffer<U>table,stage_table,undo;Buffer<Control>control;
 Impl(Seed s,Options o,int d):seed(std::move(s)),opts(o),device(d),head(genesis(seed)){validate_options(opts);need(seed.nodes.size()<=o.maximum_nodes&&seed.terms.size()<=o.maximum_terms,"seed exceeds arena capacity");}
 void alloc(){ck(cudaSetDevice(device));nodes.alloc(opts.maximum_nodes);terms.alloc(opts.maximum_terms);modules.alloc(opts.maximum_nodes);table.alloc(slots(opts.maximum_nodes));staged_nodes.alloc(opts.maximum_batch_nodes);staged_terms.alloc(opts.maximum_batch_terms);staged_modules.alloc(opts.maximum_batch_nodes);mapping.alloc(opts.maximum_batch_nodes);draft.alloc(opts.maximum_batch_nodes);request_terms.alloc(opts.maximum_batch_terms);stage_table.alloc(slots(opts.maximum_batch_nodes));undo.alloc(opts.maximum_batch_nodes);control.alloc(1);}
 Control read(){Control c;ck(cudaMemcpy(&c,control.p,sizeof c,cudaMemcpyDeviceToHost));return c;}
 void check(Control c){if(c.bad)throw std::runtime_error("online cache CUDA validation/audit code "+std::to_string(c.bad));}
 View view(){return {nodes.p,terms.p,modules.p,staged_nodes.p,staged_terms.p,staged_modules.p,head.nodes,head.terms};}
};
Arena::Arena(Seed s,Options o,int d):p_(std::make_unique<Impl>(std::move(s),o,d)){}
Arena::~Arena()=default;Arena::Arena(Arena&&)noexcept=default;Arena&Arena::operator=(Arena&&)noexcept=default;
Preparation Arena::prepare(const Stop&stop){need(p_&&!p_->failed,"online arena poisoned/moved");Busy busy(p_->busy);Preparation r;if(p_->ready){r.complete=true;r.prefix=p_->head;r.reason="already_prepared";return r;}const Stop callback=stop;auto stopped=[&]{bool value=callback&&callback();need(!p_->failed,"online arena poisoned during callback");return value;};if(stopped()){r.reason="cancelled_before_prepare";return r;}try{p_->alloc();r.CUDA_executed=true;ck(cudaMemset(p_->control.p,0,sizeof(Control)));ck(cudaMemset(p_->table.p,255,p_->table.n*sizeof(U)));if(p_->head.nodes)ck(cudaMemcpy(p_->nodes.p,p_->seed.nodes.data(),p_->head.nodes*sizeof(dl::Node),cudaMemcpyHostToDevice));if(p_->head.terms)ck(cudaMemcpy(p_->terms.p,p_->seed.terms.data(),p_->head.terms*sizeof(dl::Term),cudaMemcpyHostToDevice));if(stopped()){r.reason="cancelled_after_seed_copy";return r;}auto g=grid(std::max(p_->head.nodes,p_->head.terms));if(g){validate_seed<<<g,256>>>(p_->nodes.p,p_->head.nodes,p_->terms.p,p_->head.terms,p_->control.p);ck(cudaGetLastError());p_->check(p_->read());}if(stopped()){r.reason="cancelled_after_seed_validation";return r;}for(U i=0;i<p_->head.nodes;){U e=std::min(p_->head.nodes,i+p_->opts.rows_per_chunk);seed_chunk<<<1,1>>>(p_->nodes.p,p_->head.nodes,p_->terms.p,p_->head.terms,p_->modules.p,p_->table.p,p_->table.n,p_->opts.hash_bits,i,e,p_->control.p);ck(cudaGetLastError());p_->check(p_->read());if(stopped()){r.reason="cancelled_during_seed_index";return r;}i=e;}auto c=p_->read();need(c.stage_nodes==p_->head.nodes&&c.stage_terms==p_->head.terms,"seed canonical term layout is not exhaustive");if(stopped()){r.reason="cancelled_before_seed_publication";return r;}r.prefix=p_->head;r.reason="prepared_candidate_only";r.complete=true;p_->seed.nodes.clear();p_->seed.terms.clear();p_->ready=true;return r;}catch(const CudaError&){p_->failed=true;throw;}}
Result Arena::append(Request req,const Stop&stop){need(p_&&p_->ready&&!p_->failed,"online arena unavailable");Busy busy(p_->busy);need(req.expected==p_->head,"stale online arena prefix");need(req.nodes.size()<=p_->opts.maximum_batch_nodes&&req.terms.size()<=p_->opts.maximum_batch_terms,"request exceeds batch capacity");const Options o=p_->opts;Result r;r.before=r.after=p_->head;const Stop callback=stop;auto stopped=[&]{bool value=callback&&callback();need(!p_->failed,"online arena poisoned during callback");return value;};if(stopped()){r.reason="cancelled_before_append";return r;}bool installed=false;auto undo=[&]{if(!installed)return;rollback<<<grid(o.maximum_batch_nodes),256>>>(p_->table.p,p_->undo.p,p_->control.p);ck(cudaGetLastError());ck(cudaDeviceSynchronize());installed=false;};try{
 ck(cudaSetDevice(p_->device));r.CUDA_executed=true;ck(cudaMemset(p_->control.p,0,sizeof(Control)));ck(cudaMemset(p_->stage_table.p,255,p_->stage_table.n*sizeof(U)));
 // Typed Node assignment need not write object padding. Initialize the entire
 // possible staged output range before kernels write every semantic member.
 if(!req.nodes.empty())ck(cudaMemset(p_->staged_nodes.p,0,req.nodes.size()*sizeof(dl::Node)));if(!req.nodes.empty())ck(cudaMemcpy(p_->draft.p,req.nodes.data(),req.nodes.size()*sizeof(Draft),cudaMemcpyHostToDevice));if(!req.terms.empty())ck(cudaMemcpy(p_->request_terms.p,req.terms.data(),req.terms.size()*sizeof(dl::Term),cudaMemcpyHostToDevice));if(stopped()){r.reason="cancelled_after_request_copy";return r;}unsigned g=grid(std::max(req.nodes.size(),req.terms.size()));if(g){validate_request<<<g,256>>>(p_->draft.p,req.nodes.size(),p_->request_terms.p,req.terms.size(),p_->head.nodes,p_->control.p);ck(cudaGetLastError());p_->check(p_->read());}if(stopped()){r.reason="cancelled_after_request_validation";return r;}
 for(U i=0;i<req.nodes.size();){U e=std::min<U>(req.nodes.size(),i+o.rows_per_chunk);stage<<<1,1>>>(p_->draft.p,p_->request_terms.p,p_->mapping.p,p_->view(),p_->staged_nodes.p,p_->staged_terms.p,p_->staged_modules.p,p_->table.p,p_->table.n,p_->stage_table.p,p_->stage_table.n,std::min(o.maximum_batch_nodes,o.maximum_nodes-p_->head.nodes),std::min(o.maximum_batch_terms,o.maximum_terms-p_->head.terms),o.hash_bits,i,e,p_->control.p);ck(cudaGetLastError());auto c=p_->read();if(c.bad==100){r.reason="capacity_exhausted";return r;}p_->check(c);if(stopped()){r.reason="cancelled_during_staging";return r;}i=e;}
 auto c=p_->read();g=grid(std::max<U>(req.nodes.size(),c.stage_nodes));if(g){audit<<<g,256>>>(p_->draft.p,req.nodes.size(),p_->request_terms.p,p_->mapping.p,p_->view(),p_->control.p);ck(cudaGetLastError());p_->check(p_->read());}if(stopped()){r.reason="cancelled_after_mapping_audit";return r;}
 std::vector<dl::Node>ns(c.stage_nodes);std::vector<dl::Term>ts(c.stage_terms);std::vector<Module>ms(req.nodes.size());if(c.stage_nodes)ck(cudaMemcpy(ns.data(),p_->staged_nodes.p,c.stage_nodes*sizeof(dl::Node),cudaMemcpyDeviceToHost));if(c.stage_terms)ck(cudaMemcpy(ts.data(),p_->staged_terms.p,c.stage_terms*sizeof(dl::Term),cudaMemcpyDeviceToHost));if(!ms.empty())ck(cudaMemcpy(ms.data(),p_->mapping.p,ms.size()*sizeof(Module),cudaMemcpyDeviceToHost));std::optional<Extension>ext;if(c.stage_nodes)ext=make_extension(p_->head,c.stage_nodes,c.stage_terms,request_digest(req),delta_digest(ns,ts),mapping_digest(ms));if(stopped()){r.reason="cancelled_after_delta_transport";return r;}
 if(c.stage_nodes){ck(cudaMemcpy(p_->nodes.p+p_->head.nodes,p_->staged_nodes.p,c.stage_nodes*sizeof(dl::Node),cudaMemcpyDeviceToDevice));ck(cudaMemcpy(p_->modules.p+p_->head.nodes,p_->staged_modules.p,c.stage_nodes*sizeof(Module),cudaMemcpyDeviceToDevice));if(c.stage_terms)ck(cudaMemcpy(p_->terms.p+p_->head.terms,p_->staged_terms.p,c.stage_terms*sizeof(dl::Term),cudaMemcpyDeviceToDevice));if(stopped()){r.reason="cancelled_after_unpublished_suffix";return r;}installed=true;install<<<1,1>>>(p_->nodes.p,p_->terms.p,p_->head.nodes,p_->head.nodes+c.stage_nodes,p_->table.p,p_->table.n,o.hash_bits,p_->undo.p,p_->control.p);ck(cudaGetLastError());p_->check(p_->read());if(stopped()){undo();r.reason="cancelled_before_publication_rolled_back";return r;}}
 // All potentially throwing allocation/copy/hash work precedes publication.
 r.nodes=std::move(ns);r.terms=std::move(ts);r.mapping=std::move(ms);r.extension=std::move(ext);r.work=c.work;r.work.created_nodes=c.stage_nodes;r.work.created_terms=c.stage_terms;r.work.audited_rows=req.nodes.size();r.work.audited_new_nodes=c.stage_nodes;r.structural_verified=true;r.complete=true;r.reason=c.stage_nodes?"committed_structural_extension":"unchanged_structural_mapping";
 if(c.stage_nodes){Prefix after=r.extension->after;std::optional<Extension>last=r.extension; // copies may throw; old prefix still current
 r.after=after;p_->last.swap(last);std::swap(p_->head,after);r.published=true;installed=false;}return r;
 }catch(const CudaError&){p_->failed=true;throw;}catch(...){try{undo();}catch(...){p_->failed=true;}throw;}}
Prefix Arena::prefix()const{need(p_&&p_->ready&&!p_->failed,"online arena unavailable");return p_->head;}
bool Arena::current(const Prefix&x)const{return p_&&p_->ready&&!p_->failed&&p_->head==x;}
bool Arena::confirms_extension(const Prefix&b,const Prefix&a,const std::string&h)const{return p_&&p_->ready&&!p_->failed&&p_->last&&p_->head==a&&p_->last->before==b&&p_->last->after==a&&p_->last->receipt_sha256==h;}
bool Arena::confirms_extension(const Extension&e)const{return p_&&p_->last&&*p_->last==e&&confirms_extension(e.before,e.after,e.receipt_sha256);}
Snapshot Arena::snapshot()const{need(p_&&p_->ready&&!p_->failed&&!p_->busy,"online arena unavailable/busy");try{ck(cudaSetDevice(p_->device));Snapshot s;s.prefix=p_->head;s.nodes.resize(s.prefix.nodes);s.terms.resize(s.prefix.terms);s.modules.resize(s.prefix.nodes);if(s.prefix.nodes){ck(cudaMemcpy(s.nodes.data(),p_->nodes.p,s.nodes.size()*sizeof(dl::Node),cudaMemcpyDeviceToHost));ck(cudaMemcpy(s.modules.data(),p_->modules.p,s.modules.size()*sizeof(Module),cudaMemcpyDeviceToHost));}if(s.prefix.terms)ck(cudaMemcpy(s.terms.data(),p_->terms.p,s.terms.size()*sizeof(dl::Term),cudaMemcpyDeviceToHost));return s;}catch(const CudaError&){p_->failed=true;throw;}}
void Arena::poison(){if(p_)p_->failed=true;}bool Arena::poisoned()const{return !p_||p_->failed;}
}
