#include "streaming_file_hash.hpp"
#pragma once
#include "class_rank_gpu_class_apply.hpp"
#include "class_rank_gpu_leaf_partitions_receipt.hpp"
#include "class_rank_regional_model_export.hpp"
namespace apply_receipt {
using namespace leaf_receipt;namespace ca=rank_gpu_class_apply;namespace sd=rank_gpu_score_diagram;namespace ar=rank_gpu_online_cache;namespace gc=rank_gpu_dag_collect;namespace codec=rank_regional_model_export;
inline J counters(const ca::Counters&c){J j;
#define ITEM(x) j[#x]=c.x
 ITEM(states);ITEM(edges);ITEM(nodes);ITEM(arcs);ITEM(expanded);ITEM(reduced);ITEM(terminal_states);ITEM(state_attempts);ITEM(state_hits);ITEM(open_state_hits);ITEM(unexpanded_state_hits);ITEM(state_collisions);ITEM(tuple_comparisons);ITEM(node_attempts);ITEM(node_hits);ITEM(node_collisions);ITEM(equal_child_reductions);ITEM(arc_merges);ITEM(native_margin_calls);ITEM(native_probability_calls);ITEM(native_rows);ITEM(native_margin_words);ITEM(native_probability_words);ITEM(audited_states);ITEM(audited_transitions);ITEM(audited_nodes);
#undef ITEM
 return j;}
inline J describe(const ca::Result&r){return J{{"complete",r.complete},{"CUDA_executed",r.CUDA_executed},{"local_semantics_audited",r.local_semantics_audited},{"reason",r.reason},{"root",r.root},{"source_binding",r.source_binding},{"domain_binding",r.domain_binding},{"score_pool_sha256",r.score_pool_sha256},{"score_pool_identity_scheme","seven-score-pool-canonical-words-v1"},{"score_input_binding",r.score_input_binding},{"score_input_scheme",r.score_input_scheme},{"counters",counters(r.counters)},{"owned_device_peak_bytes",r.owned_device_peak_bytes},{"native_contract",r.native_contract_json.empty()?J():J::parse(r.native_contract_json)}};}
inline J describe(const ca::Lowered&r){return J{{"complete",r.complete},{"CUDA_executed",r.CUDA_executed},{"reason",r.reason},{"drafts",r.drafts.size()},{"root",r.root},{"audited_nodes",r.audited_nodes},{"audited_numeric_segments",r.audited_numeric_segments},{"audited_category_values",r.audited_category_values},{"owned_device_peak_bytes",r.owned_device_peak_bytes},{"graph_questions_restricted_to_literal_source_predicates",false}};}
inline J describe(const ca::QuotientAudit&r){return J{{"complete",r.complete},{"CUDA_executed",r.CUDA_executed},{"reason",r.reason},{"cells",r.cells},{"native_rows",r.native_rows},{"owned_device_peak_bytes",r.owned_device_peak_bytes}};}
inline J payload(const ca::Result&r){J j=describe(r),nodes=J::array(),arcs=J::array(),states=J::array(),edges=J::array();for(const auto&n:r.nodes)nodes.push_back(J{{"kind",n.kind},{"dimension",n.dimension},{"label",n.score_bits},{"first_arc",n.first_arc},{"arc_count",n.arc_count}});auto append=[](J&to,const ca::Arc&a){to.push_back(J{{"lo",a.lo},{"hi",a.hi},{"allowed",a.allowed},{"child",a.child}});};for(const auto&a:r.arcs)append(arcs,a);for(const auto&a:r.edges)append(edges,a);for(const auto&s:r.states)states.push_back(J{{"tuple",s.tuple},{"level",s.level},{"status",s.status},{"result",s.result},{"first_edge",s.first_edge},{"edge_count",s.edge_count},{"witness_ranks",s.witness.rank},{"witness_categories",s.witness.categories},{"native_probability_bits",s.probability_bits},{"native_label",s.label}});j["format"]="joint-native-class-apply-evidence-1";j["domain"]=box(r.domain);j["nodes"]=nodes;j["arcs"]=arcs;j["states"]=states;j["edges"]=edges;j["import_is_not_class_authority"]=true;return j;}
struct Canonical {codec::Model model;ar::Work interning;ar::Module root_module;ca::U arena_bytes=0;std::string collector_input_sha256,collector_output_sha256;};
inline Canonical canonical(const ca::Result&r,const lp::Result&p,ca::Lowered lowered,const std::string&nonce,ca::U cap=128ull*1024*1024){need(lowered.complete&&lowered.root<lowered.drafts.size(),"class lowering incomplete");Canonical out;ar::Snapshot graph;std::string authority=dpnative::sha256(r.source_binding+r.domain_binding+r.score_pool_sha256+r.native_contract_json);{
 ar::Options o;o.maximum_nodes=o.maximum_batch_nodes=lowered.drafts.size();o.maximum_terms=o.maximum_batch_terms=0;o.maximum_device_bytes=cap;out.arena_bytes=ar::device_bytes(o);ar::Arena arena({{},{},authority,nonce},o);auto prepared=arena.prepare();need(prepared.complete,"class arena preparation incomplete");auto added=arena.append({arena.prefix(),std::move(lowered.drafts),{}});need(added.complete&&added.structural_verified&&lowered.root<added.mapping.size(),"class arena append incomplete");out.interning=added.work;out.root_module=added.mapping[lowered.root];graph=arena.snapshot();}
 gc::Options co;co.maximum_device_bytes=cap;auto compact=gc::collect({std::move(graph.nodes),std::move(graph.terms),{out.root_module.id},authority},co);need(compact.complete&&compact.structural_verified&&compact.roots.size()==1&&compact.terms.empty(),"class root collection incomplete");out.collector_input_sha256=compact.input_sha256;out.collector_output_sha256=compact.output_sha256;out.model.source_sha256=p.source_sha256;out.model.rank_cut_bits=p.rank_cut_bits;out.model.rank_sha256=codec::rank_digest(p.rank_cut_bits);out.model.scope.lo=p.domain.lo;out.model.scope.hi=p.domain.hi;out.model.scope.allowed=p.domain.allowed;out.model.root=compact.roots[0];out.model.nodes=std::move(compact.nodes);return out;}
inline J build(const fs::path&source){return bind(source);}
}
