#include "class_rank_gpu_class_apply.hpp"
#include "class_rank_gpu_score_source_apply.hpp"
#include "class_rank_gpu_score_pool_identity.hpp"
#include "class_io.hpp"
#include "class_xgboost.hpp"
#include <cuda_runtime.h>
#include <algorithm>
#include <cfloat>
#include <climits>
namespace rank_gpu_class_apply {namespace {
using B=sd::b::Box;namespace ar=rank_gpu_online_cache;
void need(bool ok,const char*s){if(!ok)throw std::invalid_argument(s);}
void cu(cudaError_t e){if(e!=cudaSuccess)throw std::runtime_error(cudaGetErrorString(e));}
U mul(U a,U b){need(!b||a<=none/b,"Apply byte product overflow");return a*b;}
U add(U a,U b){need(b<=none-a,"Apply byte sum overflow");return a+b;}
struct Budget {U cap,used=0,peak=0;void take(U n){need(n<=cap-used,"Apply device-byte cap");used+=n;peak=std::max(peak,used);}};
template<class T>struct Buf {Budget&b;U n,bytes;T*p=nullptr;Buf(Budget&owner,U count):b(owner),n(count),bytes(mul(count,sizeof(T))){b.take(bytes);if(bytes){auto e=cudaMalloc(reinterpret_cast<void**>(&p),bytes);if(e!=cudaSuccess){b.used-=bytes;cu(e);}e=cudaMemset(p,0,bytes);if(e!=cudaSuccess){cudaFree(p);b.used-=bytes;cu(e);}}}~Buf(){if(p)cudaFree(p);b.used-=bytes;}Buf(const Buf&)=delete;void put(const T*x){if(bytes)cu(cudaMemcpy(p,x,bytes,cudaMemcpyHostToDevice));}std::vector<T>get(U count){need(count<=n,"Apply download extent");std::vector<T>x(count);if(count)cu(cudaMemcpy(x.data(),p,count*sizeof(T),cudaMemcpyDeviceToHost));return x;}};
unsigned blocks(U n){need(n&&n<=U(INT_MAX)*128,"Apply launch extent");return unsigned((n+127)/128);}
struct Profile {int offsets[10]{},counts[10]{};};
struct Meta {Counters c;U cursor=0,root=none;int bad=0,cap=0;};
struct Work {Options o;B domain;const Node*score;const Arc*score_arcs;U score_count,score_arc_count;const U*score_roots;State*states;Arc*edges;Node*nodes;Arc*arcs;U*state_heads;U*node_heads;U*terminals;Arc*scratch;Meta*m;};
__device__ void fail(Meta*m,int n){atomicCAS(&m->bad,0,n);}
__device__ U mix(U h,U x){return (h^x)*1099511628211ull;}
__device__ unsigned level(Work w,const U*t){unsigned d=12;for(int c=0;c<7;++c){if(t[c]>=w.score_count){fail(w.m,1);return 12;}const auto&n=w.score[t[c]];if(n.kind)d=min(d,n.dimension);}return d;}
__device__ U intern_state(Work w,const U*t,const Point&p){auto&m=*w.m;++m.c.state_attempts;unsigned d=level(w,t);if(m.bad)return none;U h=mix(1469598103934665603ull,d);for(int c=0;c<7;++c)h=mix(h,t[c]);U bucket=h%w.o.state_buckets;
 if(w.o.state_cache)for(U id=w.state_heads[bucket];id!=none;id=w.states[id].hash_next){const auto&s=w.states[id];bool equal=s.level==d;for(int c=0;equal&&c<7;++c){++m.c.tuple_comparisons;equal=s.tuple[c]==t[c];}if(equal){++m.c.state_hits;if(s.result==none)++m.c.open_state_hits;if(s.status==0)++m.c.unexpanded_state_hits;return id;}++m.c.state_collisions;}
 if(m.c.states==w.o.maximum_states){m.cap=1;return none;}U id=m.c.states++;State s{};for(int c=0;c<7;++c)s.tuple[c]=t[c];s.witness=p;s.level=d;s.hash_next=w.state_heads[bucket];w.states[id]=s;w.state_heads[bucket]=id;return id;
}
__device__ U select_score(Work w,U id,unsigned d,int rank,U category){const auto&n=w.score[id];if(!n.kind||n.dimension>d)return id;if(n.dimension!=d){fail(w.m,2);return none;}U found=none,count=0;for(U j=0;j<n.arc_count;++j){const auto&a=w.score_arcs[n.first_arc+j];if(d<10?(rank>=a.lo&&rank<=a.hi):bool(category&a.allowed)){found=a.child;++count;}}if(count!=1)fail(w.m,3);return found;}
__device__ bool add_edge(Work w,State&s,Arc a){if(s.level<10&&s.edge_count){auto&z=w.edges[s.first_edge+s.edge_count-1];if(z.child==a.child&&z.hi+1==a.lo){z.hi=a.hi;++w.m->c.arc_merges;return true;}}if(s.level>=10)for(U j=0;j<s.edge_count;++j){auto&z=w.edges[s.first_edge+j];if(z.child==a.child){z.allowed|=a.allowed;++w.m->c.arc_merges;return true;}}
 if(w.m->c.edges==w.o.maximum_edges){w.m->cap=2;return false;}w.edges[w.m->c.edges++]=a;++s.edge_count;return true;}
__global__ void initialize(Work w){if(blockIdx.x||threadIdx.x)return;for(U j=0;j<w.o.state_buckets;++j)w.state_heads[j]=none;for(U j=0;j<w.o.node_buckets;++j)w.node_heads[j]=none;Point p{};for(int d=0;d<10;++d)p.rank[d]=w.domain.lo[d];U a=w.domain.allowed&sd::b::wilderness,z=w.domain.allowed&sd::b::soil;p.categories=(a&(~a+1))|(z&(~z+1));w.m->root=intern_state(w,w.score_roots,p);}
__global__ void expand(Work w,U limit){if(blockIdx.x||threadIdx.x)return;auto&m=*w.m;for(U done=0;done<limit&&m.cursor<m.c.states;++done){U id=m.cursor;auto&s=w.states[id];if(s.level==12){s.status=2;w.terminals[m.c.terminal_states++]=id;}else{s.first_edge=m.c.edges;unsigned d=s.level;
 if(d<10){int at=w.domain.lo[d],last=w.domain.hi[d];while(at<=last){int next=last+1;for(int c=0;c<7;++c){const auto&n=w.score[s.tuple[c]];if(n.kind&&n.dimension==d)for(U j=0;j<n.arc_count;++j){const auto&a=w.score_arcs[n.first_arc+j];if(a.lo>at)next=min(next,a.lo);if(a.hi+1>at)next=min(next,a.hi+1);}}U tuple[7];for(int c=0;c<7;++c)tuple[c]=select_score(w,s.tuple[c],d,at,0);Point p=s.witness;p.rank[d]=at;U child=intern_state(w,tuple,p);if(m.bad||m.cap)return;if(w.states[child].level<=d){m.bad=4;return;}Arc a{};a.lo=at;a.hi=next-1;a.child=child;if(!add_edge(w,s,a))return;at=next;}}
 else{U group=d==10?sd::b::wilderness:sd::b::soil,allowed=w.domain.allowed&group;while(allowed){U bit=allowed&(~allowed+1);allowed^=bit;U tuple[7];for(int c=0;c<7;++c)tuple[c]=select_score(w,s.tuple[c],d,0,bit);Point p=s.witness;p.categories=(p.categories&~group)|bit;U child=intern_state(w,tuple,p);if(m.bad||m.cap)return;if(w.states[child].level<=d){m.bad=4;return;}Arc a{};a.allowed=bit;a.child=child;if(!add_edge(w,s,a))return;}}s.status=1;}++m.cursor;++m.c.expanded;}}
__device__ bool arc_equal(const Arc&a,const Arc&b){return a.lo==b.lo&&a.hi==b.hi&&a.allowed==b.allowed&&a.child==b.child;}
__device__ U intern_node(Work w,unsigned kind,unsigned d,unsigned label,U count){auto&m=*w.m;++m.c.node_attempts;U h=mix(mix(mix(1469598103934665603ull,kind),d),label);for(U j=0;j<count;++j){auto a=w.scratch[j];h=mix(mix(mix(mix(h,unsigned(a.lo)),unsigned(a.hi)),a.allowed),a.child);}U bucket=h%w.o.node_buckets;
 for(U id=w.node_heads[bucket];id!=none;id=w.nodes[id].hash_next){const auto&n=w.nodes[id];bool equal=n.kind==kind&&n.dimension==d&&n.score_bits==label&&n.arc_count==count;for(U j=0;equal&&j<count;++j)equal=arc_equal(w.arcs[n.first_arc+j],w.scratch[j]);if(equal){++m.c.node_hits;return id;}++m.c.node_collisions;}
 if(m.c.nodes==w.o.maximum_nodes){m.cap=3;return none;}if(count>w.o.maximum_arcs-m.c.arcs){m.cap=4;return none;}U id=m.c.nodes++;Node n{};n.kind=kind;n.dimension=d;n.score_bits=label;n.first_arc=m.c.arcs;n.arc_count=count;n.hash_next=w.node_heads[bucket];for(U j=0;j<count;++j)w.arcs[m.c.arcs++]=w.scratch[j];w.nodes[id]=n;w.node_heads[bucket]=id;return id;
}
__global__ void reduce_dimension(Work w,unsigned dimension){if(blockIdx.x||threadIdx.x)return;auto&m=*w.m;for(U id=0;id<m.c.states;++id){auto&s=w.states[id];if(s.level!=dimension)continue;if(dimension==12){if(s.status!=2||s.label<0||s.label>=7){m.bad=5;return;}s.result=intern_node(w,0,12,unsigned(s.label),0);}else{if(s.status!=1||!s.edge_count){m.bad=6;return;}U count=0;for(U j=0;j<s.edge_count;++j){Arc a=w.edges[s.first_edge+j];if(a.child>=m.c.states||w.states[a.child].level<=dimension||w.states[a.child].status!=3){m.bad=7;return;}a.child=w.states[a.child].result;if(dimension<10&&count&&w.scratch[count-1].child==a.child){w.scratch[count-1].hi=a.hi;++m.c.arc_merges;continue;}bool found=false;if(dimension>=10)for(U k=0;k<count;++k)if(w.scratch[k].child==a.child){w.scratch[k].allowed|=a.allowed;found=true;++m.c.arc_merges;break;}if(!found)w.scratch[count++]=a;}if(count==1){s.result=w.scratch[0].child;++m.c.equal_child_reductions;}else s.result=intern_node(w,1,dimension,0,count);}if(m.bad||m.cap)return;s.status=3;++m.c.reduced;}}
__global__ void profile_check(Profile p,const unsigned*cuts,B domain,Meta*m){if(blockIdx.x||threadIdx.x)return;for(int d=0;d<10;++d){if(domain.hi[d]!=p.counts[d]||domain.lo[d]!=(p.counts[d]&&cuts[p.offsets[d]]==0xff7fffffu)){fail(m,8);return;}for(int j=0;j<p.counts[d];++j){float x=__uint_as_float(cuts[p.offsets[d]+j]);if(!isfinite(x)||(x==0.f&&cuts[p.offsets[d]+j])||(j&&!(__uint_as_float(cuts[p.offsets[d]+j-1])<x))){fail(m,9);return;}}}}
__device__ U route(const Node*nodes,U nn,const Arc*arcs,U root,const Point&p,Meta*m){U at=root;for(int step=0;step<14;++step){if(at>=nn){fail(m,10);return none;}const auto&n=nodes[at];if(!n.kind)return at;U next=none,hits=0;for(U j=0;j<n.arc_count;++j){const auto&a=arcs[n.first_arc+j];bool hit=n.dimension<10?p.rank[n.dimension]>=a.lo&&p.rank[n.dimension]<=a.hi:bool(p.categories&a.allowed);if(hit){next=a.child;++hits;}}if(hits!=1||next>=at){fail(m,11);return none;}at=next;}fail(m,12);return none;}
__global__ void witnesses(Work w,Profile profile,const unsigned*cuts,U base,U count,float*raw){U row=U(blockIdx.x)*blockDim.x+threadIdx.x;if(row>=count)return;const auto&s=w.states[w.terminals[base+row]];const auto&p=s.witness;for(int f=0;f<54;++f)raw[row*54+f]=0.f;for(int d=0;d<10;++d){int rank=p.rank[d];if(rank<w.domain.lo[d]||rank>w.domain.hi[d]){fail(w.m,13);return;}float x=rank?__uint_as_float(cuts[profile.offsets[d]+rank-1]):-FLT_MAX;raw[row*54+d]=x;int actual=0;for(int j=0;j<profile.counts[d];++j)actual+=x>=__uint_as_float(cuts[profile.offsets[d]+j]);if(actual!=rank)fail(w.m,14);}if((p.categories&~w.domain.allowed)||__popcll(p.categories&sd::b::wilderness)!=1||__popcll(p.categories&sd::b::soil)!=1){fail(w.m,15);return;}for(int k=0;k<44;++k)raw[row*54+10+k]=float((p.categories>>k)&1);
 for(int c=0;c<7;++c){U at=route(w.score,w.score_count,w.score_arcs,w.score_roots[c],p,w.m);if(at==none||at!=s.tuple[c]||w.score[at].kind){fail(w.m,16);return;}}
}
__global__ void check_margins(Work w,U base,U count,const float*native){U row=U(blockIdx.x)*blockDim.x+threadIdx.x;if(row>=count)return;const auto&s=w.states[w.terminals[base+row]];for(int c=0;c<7;++c)if(__float_as_uint(native[row*7+c])!=w.score[s.tuple[c]].score_bits)fail(w.m,17);}
__global__ void label_probabilities(Work w,U base,U count,const float*native){U row=U(blockIdx.x)*blockDim.x+threadIdx.x;if(row>=count)return;auto&s=w.states[w.terminals[base+row]];int best=0;bool positive=false;for(int c=0;c<7;++c){float p=native[row*7+c];if(!isfinite(p)||p<0.f||p>1.f){fail(w.m,18);return;}positive=positive||p>0.f;s.probability_bits[c]=__float_as_uint(p);if(p>native[row*7+best])best=c;}if(!positive){fail(w.m,19);return;}s.label=best;}
const char*cap_reason(int code){switch(code){case 1:return "apply_state_cap";case 2:return "apply_edge_cap";case 3:return "class_node_cap";case 4:return "class_arc_cap";default:return "unknown_cap";}}
Profile profile(const lp::Result&p,std::vector<unsigned>&cuts){Profile result{};for(int d=0;d<10;++d){need(cuts.size()<=INT_MAX&&p.rank_cut_bits[d].size()<=4096,"Apply rank table extent");result.offsets[d]=int(cuts.size());result.counts[d]=int(p.rank_cut_bits[d].size());cuts.insert(cuts.end(),p.rank_cut_bits[d].begin(),p.rank_cut_bits[d].end());}return result;}
std::string score_pool(const sd::Result&s){return rank_gpu_score_identity::digest(s);}
std::string contract(dpnative::XGBoostOracle&o,const std::string&lib,const lp::Result&p,int device){using J=dpnative::json;need(dpnative::sha256(dpnative::read_text(lib))=="462aa6331ecb178df8d10f16612c865ae70f571c248138e50c8a9eb4bc007dd4","Apply native library unsupported");cudaDeviceProp prop{};int driver=0,runtime=0;cu(cudaGetDeviceProperties(&prop,device));cu(cudaDriverGetVersion(&driver));cu(cudaRuntimeGetVersion(&runtime));need(prop.major==8&&prop.minor==6&&std::string(prop.name)=="NVIDIA RTX A5000 Laptop GPU"&&driver==13040&&runtime==13040,"Apply native device/runtime unsupported");auto build=J::parse(o.build_info());need(dpnative::sha256(build.dump())=="66af94fc63f2d242b37516a7b27ee0c8270cdd8de874dfc9c0315e9d3775379d","Apply native build unsupported");return J{{"schema","pinned-native-score-tuple-contract-1"},{"source_sha256",p.source_sha256},{"library_sha256",p.library_sha256},{"version",o.version()},{"device",device},{"gpu",prop.name},{"compute_capability",{prop.major,prop.minor}},{"cuda_driver",driver},{"cuda_runtime",runtime},{"native_build_info",build},{"native_configuration",J::parse(o.configuration_json())},{"source_revision","v3.4.1"},{"transform_source","https://github.com/dmlc/xgboost/blob/v3.4.1/src/objective/multiclass_obj.cu#L138-L149"},{"softmax_source","https://github.com/dmlc/xgboost/blob/v3.4.1/src/common/math.h#L63-L80"},{"premise","fixed native transform is deterministic and operates only on each ordered seven-word row"},{"native_semantic_premise_trusted",true},{"loaded_image_recaptured_in_this_process",false},{"raw_margin_argmax_used",false},{"gap_RuntimeGate_used",false},{"Lean_or_CUDA_refinement_proved",false}}.dump();}
}
U planned_device_bytes(const sd::Result&s,U cuts,const Options&o){need(o.maximum_states&&o.maximum_edges&&o.maximum_nodes&&o.maximum_arcs&&o.state_buckets&&o.node_buckets&&o.states_per_launch&&o.native_batch_rows&&o.native_batch_rows<=1048576,"Apply invalid capacity option");U n=4096;n=add(n,mul(s.nodes.size(),sizeof(Node)));n=add(n,mul(s.arcs.size(),sizeof(Arc)));n=add(n,mul(cuts,sizeof(unsigned)));n=add(n,mul(o.maximum_states,sizeof(State)+sizeof(U)));n=add(n,mul(o.maximum_edges,sizeof(Arc)));n=add(n,mul(o.maximum_nodes,sizeof(Node)));n=add(n,mul(o.maximum_arcs,sizeof(Arc)));n=add(n,mul(add(o.state_buckets,o.node_buckets),sizeof(U)));n=add(n,mul(add(mul(s.arcs.size(),2),44),sizeof(Arc)));n=add(n,mul(mul(o.native_batch_rows,54),sizeof(float)));return n;}
static Result construct_impl(const sd::Input*input,const sd::Result&scores,const lp::Result&partitions,const std::string&library,const std::string&model,Options o,const Stop&stop,int device){sd::validate_transport(scores);need(partitions.complete&&partitions.library_sha256=="462aa6331ecb178df8d10f16612c865ae70f571c248138e50c8a9eb4bc007dd4"&&partitions.source.binding==scores.source_binding&&partitions.rank_sha256==scores.domain_binding&&partitions.source_sha256==dpnative::sha256(dpnative::read_text(model)),"Apply source/score binding differs");Result out;out.source_binding=scores.source_binding;out.domain_binding=scores.domain_binding;out.score_pool_sha256=score_pool(scores);out.domain=scores.domain;std::vector<unsigned>host_cuts;Profile p=profile(partitions,host_cuts);U planned=planned_device_bytes(scores,host_cuts.size(),o);if(planned>o.maximum_device_bytes){out.reason="apply_device_cap";return out;}auto halt=[&]{return stop&&stop();};if(halt()){out.reason="cancelled_before_apply";return out;}if(input){auto audit=sd::audit_factors(*input,scores,{16777216,o.maximum_device_bytes},stop,device);out.CUDA_executed=audit.CUDA_executed;out.owned_device_peak_bytes=audit.owned_device_peak_bytes;if(!audit.complete){out.reason="score_input_audit_"+audit.reason;return out;}}
 cu(cudaSetDevice(device));dpnative::XGBoostOracle oracle(library,model,54,7,device);out.native_contract_json=contract(oracle,library,partitions,device);Budget budget{o.maximum_device_bytes};Buf<Node>sn(budget,scores.nodes.size()),nodes(budget,o.maximum_nodes);Buf<Arc>sa(budget,scores.arcs.size()),edges(budget,o.maximum_edges),arcs(budget,o.maximum_arcs),scratch(budget,scores.arcs.size()*2+44);Buf<U>roots(budget,7),heads(budget,o.state_buckets),nodeheads(budget,o.node_buckets),terminals(budget,o.maximum_states);Buf<State>states(budget,o.maximum_states);Buf<unsigned>cuts(budget,host_cuts.size());Buf<float>raw(budget,o.native_batch_rows*54);Buf<Meta>meta(budget,1);sn.put(scores.nodes.data());sa.put(scores.arcs.data());roots.put(scores.roots.data());cuts.put(host_cuts.data());Work w{o,scores.domain,sn.p,sa.p,scores.nodes.size(),scores.arcs.size(),roots.p,states.p,edges.p,nodes.p,arcs.p,heads.p,nodeheads.p,terminals.p,scratch.p,meta.p};Meta m{};
 auto checked=[&]{cu(cudaGetLastError());m=meta.get(1)[0];if(m.bad)throw std::runtime_error("CUDA Apply failed: "+std::to_string(m.bad));};
 auto finish=[&](const char*why){out.reason=why;out.counters=m.c;out.owned_device_peak_bytes=std::max(out.owned_device_peak_bytes,budget.peak);out.nodes=nodes.get(m.c.nodes);out.arcs=arcs.get(m.c.arcs);out.states=states.get(m.c.states);out.edges=edges.get(m.c.edges);return out;};
 profile_check<<<1,1>>>(p,cuts.p,scores.domain,meta.p);out.CUDA_executed=true;checked();initialize<<<1,1>>>(w);checked();if(m.cap)return finish(cap_reason(m.cap));while(m.cursor<m.c.states){if(halt())return finish("cancelled_apply_expansion");expand<<<1,1>>>(w,o.states_per_launch);checked();if(m.cap)return finish(cap_reason(m.cap));}
 for(U base=0;base<m.c.terminal_states;base+=o.native_batch_rows){if(halt())return finish("cancelled_native_tuple_queries");U n=std::min(o.native_batch_rows,m.c.terminal_states-base);witnesses<<<blocks(n),128>>>(w,p,cuts.p,base,n,raw.p);checked();const float*margin=oracle.predict_values(raw.p,n,true);check_margins<<<blocks(n),128>>>(w,base,n,margin);checked();const float*prob=oracle.predict_values(raw.p,n,false);label_probabilities<<<blocks(n),128>>>(w,base,n,prob);checked();++m.c.native_margin_calls;++m.c.native_probability_calls;m.c.native_rows+=n;m.c.native_margin_words+=n*7;m.c.native_probability_words+=n*7;meta.put(&m);}
 for(int d=12;d>=0;--d){if(halt())return finish("cancelled_apply_reduction");reduce_dimension<<<1,1>>>(w,unsigned(d));checked();if(m.cap)return finish(cap_reason(m.cap));}need(m.c.reduced==m.c.states&&m.root<m.c.states,"Apply reduced state count differs");if(halt())return finish("cancelled_before_apply_publication");out=finish("complete_joint_native_class_Apply_pending_independent_full_grid");out.root=out.states[m.root].result;out.complete=true;need(out.root<out.nodes.size(),"Apply root invalid");need(partitions.source_sha256==dpnative::sha256(dpnative::read_text(model))&&out.native_contract_json==contract(oracle,library,partitions,device),"Apply source/native identity changed");return out;
}
namespace {
__device__ bool same_box(const B&a,const B&b){if(a.allowed!=b.allowed)return false;for(int d=0;d<10;++d)if(a.lo[d]!=b.lo[d]||a.hi[d]!=b.hi[d])return false;return true;}
__device__ bool subset(const Arc&a,const Arc&b,unsigned d){return d<10?a.lo>=b.lo&&a.hi<=b.hi:(a.allowed&~b.allowed)==0;}
__device__ bool partition(const Arc*a,U count,unsigned d,B box){if(!count||d>=12)return false;int next=d<10?box.lo[d]:0,last=0;U seen=0;for(U j=0;j<count;++j){const auto&e=a[j];if(d<10){if(e.allowed||e.lo!=next||e.hi<e.lo||e.hi>box.hi[d])return false;next=e.hi+1;}else{U group=d==10?sd::b::wilderness:sd::b::soil;int first=__ffsll(e.allowed);if(e.lo||e.hi||!e.allowed||(e.allowed&~(box.allowed&group))||(seen&e.allowed)||first<=last)return false;seen|=e.allowed;last=first;}}return d<10?next==box.hi[d]+1:seen==(box.allowed&(d==10?sd::b::wilderness:sd::b::soil));}
__global__ void check_class_nodes(B domain,const Node*nodes,U nn,const Arc*arcs,U na,Meta*m){U id=U(blockIdx.x)*blockDim.x+threadIdx.x;if(id>=nn)return;const auto&n=nodes[id];if(n.kind>1||n.reserved||n.first_arc>na||n.arc_count>na-n.first_arc){fail(m,30);return;}if(!n.kind){if(n.dimension!=12||n.arc_count||n.score_bits>=7){fail(m,31);return;}}else{if(n.score_bits||n.arc_count<2||!partition(arcs+n.first_arc,n.arc_count,n.dimension,domain)){fail(m,32);return;}for(U j=0;j<n.arc_count;++j){auto a=arcs[n.first_arc+j];if(a.child>=id||(nodes[a.child].kind&&nodes[a.child].dimension<=n.dimension)){fail(m,33);return;}}}atomicAdd(reinterpret_cast<unsigned long long*>(&m->c.audited_nodes),1ull);}
__global__ void check_states(Work w,U ns,U ne,U nn,U na,U root,B other){U id=U(blockIdx.x)*blockDim.x+threadIdx.x;if(id>=ns)return;const auto&s=w.states[id];if(!same_box(w.domain,other)||s.status!=3||s.level!=level(w,s.tuple.data())||s.result>=nn||s.first_edge>ne||s.edge_count>ne-s.first_edge){fail(w.m,34);return;}if(!id){if(root!=s.result){fail(w.m,35);return;}for(int c=0;c<7;++c)if(s.tuple[c]!=w.score_roots[c]){fail(w.m,36);return;}}
 if(s.level==12){if(s.edge_count||s.label<0||s.label>=7||w.nodes[s.result].kind||w.nodes[s.result].score_bits!=unsigned(s.label)){fail(w.m,37);return;}int best=0;bool positive=false;for(int c=0;c<7;++c){float p=__uint_as_float(s.probability_bits[c]);if(!isfinite(p)||p<0.f||p>1.f){fail(w.m,38);return;}positive=positive||p>0.f;if(p>__uint_as_float(s.probability_bits[best]))best=c;}if(!positive||best!=s.label){fail(w.m,39);return;}}
 else{if(s.label!=-1||!partition(w.edges+s.first_edge,s.edge_count,s.level,w.domain)){fail(w.m,40);return;}U common=none;bool same=true;for(U j=0;j<s.edge_count;++j){const auto&e=w.edges[s.first_edge+j];if(e.child>=ns||w.states[e.child].level<=s.level){fail(w.m,41);return;}const auto&child=w.states[e.child];if(!j)common=child.result;else same=same&&common==child.result;for(int c=0;c<7;++c){U expected=s.tuple[c];const auto&n=w.score[expected];if(n.kind&&n.dimension==s.level){U hits=0;for(U k=0;k<n.arc_count;++k){const auto&a=w.score_arcs[n.first_arc+k];if(subset(e,a,s.level)){expected=a.child;++hits;}}if(hits!=1){fail(w.m,42);return;}}if(child.tuple[c]!=expected){fail(w.m,43);return;}}}
 if(same){if(s.result!=common){fail(w.m,44);return;}}else{const auto&n=w.nodes[s.result];if(n.kind!=1||n.dimension!=s.level||n.first_arc>na||n.arc_count>na-n.first_arc){fail(w.m,45);return;}for(U j=0;j<s.edge_count;++j){const auto&e=w.edges[s.first_edge+j];U hits=0;for(U k=0;k<n.arc_count;++k){const auto&a=w.arcs[n.first_arc+k];if(subset(e,a,s.level)&&a.child==w.states[e.child].result)++hits;}if(hits!=1){fail(w.m,46);return;}}}
 atomicAdd(reinterpret_cast<unsigned long long*>(&w.m->c.audited_transitions),static_cast<unsigned long long>(s.edge_count));}
 atomicAdd(reinterpret_cast<unsigned long long*>(&w.m->c.audited_states),1ull);
}
std::pair<Counters,U>local_checks(const sd::Result&s,const Result&r,U cap,int device){sd::validate_transport(s);need(r.complete&&r.root<r.nodes.size()&&!r.states.empty()&&r.source_binding==s.source_binding&&r.domain_binding==s.domain_binding&&r.score_pool_sha256==score_pool(s)&&r.nodes.size()==r.counters.nodes&&r.arcs.size()==r.counters.arcs&&r.states.size()==r.counters.states&&r.edges.size()==r.counters.edges,"Apply local audit transport/binding");cu(cudaSetDevice(device));Budget b{cap};Buf<Node>sn(b,s.nodes.size()),nodes(b,r.nodes.size());Buf<Arc>sa(b,s.arcs.size()),arcs(b,r.arcs.size()),edges(b,r.edges.size());Buf<State>states(b,r.states.size());Buf<U>roots(b,7);Buf<Meta>m(b,1);sn.put(s.nodes.data());sa.put(s.arcs.data());nodes.put(r.nodes.data());arcs.put(r.arcs.data());edges.put(r.edges.data());states.put(r.states.data());roots.put(s.roots.data());Work w{{},s.domain,sn.p,sa.p,s.nodes.size(),s.arcs.size(),roots.p,states.p,edges.p,nodes.p,arcs.p,nullptr,nullptr,nullptr,nullptr,m.p};check_class_nodes<<<blocks(r.nodes.size()),128>>>(s.domain,nodes.p,r.nodes.size(),arcs.p,r.arcs.size(),m.p);cu(cudaGetLastError());auto status=m.get(1)[0];need(!status.bad,"Apply class-node audit failed");check_states<<<blocks(r.states.size()),128>>>(w,r.states.size(),r.edges.size(),r.nodes.size(),r.arcs.size(),r.root,r.domain);cu(cudaGetLastError());status=m.get(1)[0];if(status.bad)throw std::runtime_error("Apply local semantic audit failed: "+std::to_string(status.bad));need(status.c.audited_states==r.states.size()&&status.c.audited_transitions==r.edges.size()&&status.c.audited_nodes==r.nodes.size(),"Apply local audit counts differ");return {status.c,b.peak};}
}
void audit_local(const sd::Result&s,const Result&r,U cap,int device){local_checks(s,r,cap,device);}
static Result finish_construct(const sd::Result&scores,Result r,Options o,const Stop&stop,int device){if(!r.complete)return r;if(stop&&stop()){r.complete=false;r.root=none;r.reason="cancelled_before_local_semantic_audit";return r;}auto [c,bytes]=local_checks(scores,r,o.maximum_device_bytes,device);r.counters.audited_states=c.audited_states;r.counters.audited_nodes=c.audited_nodes;r.counters.audited_transitions=c.audited_transitions;r.owned_device_peak_bytes=std::max(r.owned_device_peak_bytes,bytes);r.local_semantics_audited=true;if(stop&&stop()){r.complete=false;r.root=none;r.reason="cancelled_after_local_semantic_audit";}return r;}
Result construct(const sd::Input&input,const sd::Result&scores,const lp::Result&partitions,const std::string&library,const std::string&model,Options o,const Stop&stop,int device){auto r=construct_impl(&input,scores,partitions,library,model,o,stop,device);r.score_input_scheme="same-process-full-class-factor-universal-audit-v1";r.score_input_binding=dpnative::sha256(r.score_input_scheme+input.factors.source_binding+r.score_pool_sha256);return finish_construct(scores,std::move(r),o,stop,device);}
Result construct(const rank_gpu_score_source_apply::AcceptedScores&accepted,const lp::Result&partitions,const std::string&library,const std::string&model,Options o,const Stop&stop,int device){need(accepted.source_digest().size()==64&&accepted.sequence_digest().size()==64&&accepted.matches(partitions),"sequential score authority does not match complete source partitions");const auto&scores=accepted.scores();auto pool=score_pool(scores);need(accepted.graph_digest()==pool,"sequential seven-root score word digest differs");auto r=construct_impl(nullptr,scores,partitions,library,model,o,stop,device);r.score_input_scheme="same-process-source-tree-sequential-RN32-Add-universal-prefix-audits-v1";rank_gpu_score_identity::Hash h;h.text(r.score_input_scheme);h.text(accepted.source_digest());h.text(accepted.sequence_digest());h.text(accepted.graph_digest());r.score_input_binding=h.finish();need(accepted.matches(partitions)&&score_pool(scores)==pool,"sequential score authority changed during class Apply");return finish_construct(scores,std::move(r),o,stop,device);}
namespace {
struct LowerMeta {U count=0,nodes=0,numeric=0,categories=0;int bad=0,capped=0;};
__global__ void lower_count(B domain,const Node*nodes,U nn,const Arc*arcs,U cap,LowerMeta*m){if(blockIdx.x||threadIdx.x)return;U total=0;for(U id=0;id<nn;++id){const auto&n=nodes[id];U count=1;if(n.kind&&n.dimension<10)count=n.arc_count-1;else if(n.kind){int largest=0;for(U j=0;j<n.arc_count;++j)largest=max(largest,__popcll(arcs[n.first_arc+j].allowed));count=U(__popcll(domain.allowed&(n.dimension==10?sd::b::wilderness:sd::b::soil))-largest);}if(count>cap-total){m->capped=1;return;}total+=count;}m->count=total;}
__global__ void lower_build(B domain,const Node*nodes,U nn,const Arc*arcs,ar::Draft*drafts,U*starts,U*mapping,LowerMeta*m){if(blockIdx.x||threadIdx.x)return;U next=0;for(U id=0;id<nn;++id){const auto&n=nodes[id];starts[id]=next;if(!n.kind){ar::Draft d{};d.label=int(n.score_bits);drafts[next]=d;mapping[id]=next++;continue;}U fallback=n.arc_count-1;if(n.dimension>=10){int largest=-1;for(U j=0;j<n.arc_count;++j){int size=__popcll(arcs[n.first_arc+j].allowed);if(size>largest){largest=size;fallback=j;}}}U acc=mapping[arcs[n.first_arc+fallback].child];for(U j=n.arc_count;j-->0;){if(j==fallback)continue;const auto&a=arcs[n.first_arc+j];if(n.dimension<10){ar::Draft d{};d.kind=0;d.feature=int(n.dimension);d.cut_bits=__float_as_uint(float(a.hi+1));d.left={mapping[a.child],2};d.right={acc,2};drafts[next]=d;acc=next++;}else{U allowed=a.allowed;while(allowed){int bit=__ffsll(allowed)-1;allowed&=allowed-1;ar::Draft d{};d.kind=0;d.feature=10+bit;d.cut_bits=0x3f000000u;d.left={acc,2};d.right={mapping[a.child],2};drafts[next]=d;acc=next++;}}}mapping[id]=acc;}if(next!=m->count)m->bad=1;}
__global__ void lower_audit(B domain,const Node*nodes,U nn,const Arc*arcs,const ar::Draft*drafts,const U*starts,const U*mapping,LowerMeta*m){U id=U(blockIdx.x)*blockDim.x+threadIdx.x;if(id>=nn)return;const auto&n=nodes[id];U first=starts[id],root=mapping[id];if(first>=m->count||root<first||root>=m->count||(id&&first!=mapping[id-1]+1)||(id+1==nn&&root+1!=m->count)){atomicCAS(&m->bad,0,2);return;}if(!n.kind){const auto&d=drafts[root];if(root!=first||d.kind!=2||d.label!=int(n.score_bits)||d.left.kind||d.right.kind||d.term_count){atomicCAS(&m->bad,0,3);return;}}
 else{for(U at=first;at<=root;++at){const auto&d=drafts[at];if(d.kind!=0||d.label!=-1||d.term_count||d.left.kind!=2||d.right.kind!=2||d.left.id>=at||d.right.id>=at){atomicCAS(&m->bad,0,4);return;}if(n.dimension<10){float cut=__uint_as_float(d.cut_bits);if(d.feature!=int(n.dimension)||!isfinite(cut)||cut<=float(domain.lo[n.dimension])||cut>float(domain.hi[n.dimension])||float(int(cut))!=cut||d.left.id>=first){atomicCAS(&m->bad,0,5);return;}}else{int begin=n.dimension==10?10:14,end=n.dimension==10?14:54;if(d.feature<begin||d.feature>=end||d.cut_bits!=0x3f000000u||d.right.id>=first){atomicCAS(&m->bad,0,6);return;}}}
 if(n.dimension<10){for(U j=0;j<n.arc_count;++j){const auto&a=arcs[n.first_arc+j];U at=root,expected=mapping[a.child];int lo=a.lo,hi=a.hi;while(at>=first){const auto&d=drafts[at];int cut=int(__uint_as_float(d.cut_bits));if(hi<cut)at=d.left.id;else if(lo>=cut)at=d.right.id;else{if(d.left.id!=expected){atomicCAS(&m->bad,0,7);return;}lo=cut;at=d.right.id;}}if(at!=expected){atomicCAS(&m->bad,0,8);return;}}atomicAdd(reinterpret_cast<unsigned long long*>(&m->numeric),static_cast<unsigned long long>(n.arc_count));}
 else{U allowed=domain.allowed&(n.dimension==10?sd::b::wilderness:sd::b::soil);while(allowed){U bit=allowed&(~allowed+1);allowed^=bit;U expected=none,hits=0;for(U j=0;j<n.arc_count;++j)if(arcs[n.first_arc+j].allowed&bit){expected=mapping[arcs[n.first_arc+j].child];++hits;}if(hits!=1){atomicCAS(&m->bad,0,9);return;}U at=root;while(at>=first){const auto&d=drafts[at];at=(bit&(U(1)<<(d.feature-10)))?d.right.id:d.left.id;}if(at!=expected){atomicCAS(&m->bad,0,10);return;}}atomicAdd(reinterpret_cast<unsigned long long*>(&m->categories),static_cast<unsigned long long>(__popcll(domain.allowed&(n.dimension==10?sd::b::wilderness:sd::b::soil))));}}
 atomicAdd(reinterpret_cast<unsigned long long*>(&m->nodes),1ull);
}
}
Lowered lower_binary(const Result&r,U maximum_drafts,U cap,const Stop&stop,int device){need(r.complete&&r.local_semantics_audited&&r.root<r.nodes.size()&&!r.source_binding.empty()&&!r.domain_binding.empty()&&maximum_drafts,"binary lowering input/cap invalid");Lowered out;if(stop&&stop()){out.reason="cancelled_before_lowering";return out;}cu(cudaSetDevice(device));Budget b{cap};Buf<Node>nodes(b,r.nodes.size());Buf<Arc>arcs(b,r.arcs.size());Buf<U>starts(b,r.nodes.size()),map(b,r.nodes.size());Buf<Meta>validation(b,1);Buf<LowerMeta>meta(b,1);nodes.put(r.nodes.data());arcs.put(r.arcs.data());check_class_nodes<<<blocks(r.nodes.size()),128>>>(r.domain,nodes.p,r.nodes.size(),arcs.p,r.arcs.size(),validation.p);cu(cudaGetLastError());need(!validation.get(1)[0].bad,"lowering class input invalid");lower_count<<<1,1>>>(r.domain,nodes.p,r.nodes.size(),arcs.p,maximum_drafts,meta.p);cu(cudaGetLastError());auto m=meta.get(1)[0];out.CUDA_executed=true;out.owned_device_peak_bytes=b.peak;if(m.capped){out.reason="binary_draft_cap";return out;}U bytes=mul(m.count,sizeof(ar::Draft));if(bytes>cap-b.used){out.reason="binary_device_cap";return out;}if(stop&&stop()){out.reason="cancelled_after_lowering_count";return out;}Buf<ar::Draft>drafts(b,m.count);lower_build<<<1,1>>>(r.domain,nodes.p,r.nodes.size(),arcs.p,drafts.p,starts.p,map.p,meta.p);cu(cudaGetLastError());m=meta.get(1)[0];need(!m.bad,"binary lowering generation failed");lower_audit<<<blocks(r.nodes.size()),128>>>(r.domain,nodes.p,r.nodes.size(),arcs.p,drafts.p,starts.p,map.p,meta.p);cu(cudaGetLastError());m=meta.get(1)[0];if(m.bad)throw std::runtime_error("CUDA universal binary lowering failed: "+std::to_string(m.bad));out.owned_device_peak_bytes=b.peak;out.audited_nodes=m.nodes;out.audited_numeric_segments=m.numeric;out.audited_category_values=m.categories;need(m.nodes==r.nodes.size(),"binary lowering audit node coverage");if(stop&&stop()){out.reason="cancelled_after_lowering_audit";return out;}auto ids=map.get(r.nodes.size());out.root=ids[r.root];out.drafts=drafts.get(m.count);out.complete=true;out.reason="GPU_universal_numeric_segment_and_full_category_lowering_equal";return out;}
namespace {
__global__ void quotient_size(B d,B other,U cap,Meta*m){if(blockIdx.x||threadIdx.x)return;if(!same_box(d,other)||(d.allowed&~((U(1)<<44)-1))||!(d.allowed&sd::b::wilderness)||!(d.allowed&sd::b::soil)){fail(m,50);return;}U size=1;for(int k=0;k<12;++k){if(k<10&&(d.lo[k]<0||d.hi[k]>16777216||d.lo[k]>d.hi[k])){fail(m,51);return;}U radix=k<10?U(d.hi[k]-d.lo[k])+1:U(__popcll(d.allowed&(k==10?sd::b::wilderness:sd::b::soil)));if(size>cap/radix){m->cap=1;return;}size*=radix;}m->c.states=size;}
__device__ U category_at(U mask,U at){while(at--)mask&=mask-1;return mask&(~mask+1);}
__global__ void quotient_rows(B d,Profile profile,const unsigned*cuts,U base,U count,Point*points,float*raw){U row=U(blockIdx.x)*blockDim.x+threadIdx.x;if(row>=count)return;Point p{};U index=base+row;for(int k=11;k>=0;--k){U group=k==10?sd::b::wilderness:sd::b::soil,radix=k<10?U(d.hi[k]-d.lo[k])+1:U(__popcll(d.allowed&group)),value=index%radix;index/=radix;if(k<10)p.rank[k]=d.lo[k]+int(value);else p.categories|=category_at(d.allowed&group,value);}points[row]=p;for(int f=0;f<54;++f)raw[row*54+f]=f<10?(p.rank[f]?__uint_as_float(cuts[profile.offsets[f]+p.rank[f]-1]):-FLT_MAX):float((p.categories>>(f-10))&1);}
__global__ void quotient_compare(const Point*points,U count,const float*prob,const Node*nodes,U nn,const Arc*arcs,U root,Meta*m){U row=U(blockIdx.x)*blockDim.x+threadIdx.x;if(row>=count)return;int best=0;bool positive=false;for(int c=0;c<7;++c){float p=prob[row*7+c];if(!isfinite(p)||p<0.f||p>1.f){fail(m,52);return;}positive=positive||p>0.f;if(p>prob[row*7+best])best=c;}U at=route(nodes,nn,arcs,root,points[row],m);if(!positive||at==none||nodes[at].score_bits!=unsigned(best)){fail(m,53);return;}atomicAdd(reinterpret_cast<unsigned long long*>(&m->c.audited_states),1ull);}
__global__ void compare_terminals(const State*a,U an,const State*b,U bn,Meta*m){U id=U(blockIdx.x)*blockDim.x+threadIdx.x;if(id>=an||a[id].level!=12)return;U hits=0;for(U j=0;j<bn;++j){if(b[j].level!=12)continue;bool equal=true;for(int c=0;c<7;++c)equal=equal&&a[id].tuple[c]==b[j].tuple[c];if(!equal)continue;++hits;if(a[id].label!=b[j].label){fail(m,54);return;}for(int c=0;c<7;++c)if(a[id].probability_bits[c]!=b[j].probability_bits[c]){fail(m,55);return;}}if(!hits){fail(m,56);return;}atomicAdd(reinterpret_cast<unsigned long long*>(&m->c.audited_states),1ull);}
__global__ void quotient_binary_compare(const Point*points,U count,const float*prob,const rank_disk_ledger::Node*nodes,U nn,U root,Meta*m){U row=U(blockIdx.x)*blockDim.x+threadIdx.x;if(row>=count)return;int best=0;bool positive=false;for(int c=0;c<7;++c){float p=prob[row*7+c];if(!isfinite(p)||p<0.f||p>1.f){fail(m,57);return;}positive=positive||p>0.f;if(p>prob[row*7+best])best=c;}if(!positive){fail(m,58);return;}U at=root;for(U step=0;step<=nn;++step){if(at>=nn){fail(m,59);return;}const auto&n=nodes[at];if(n.id!=at){fail(m,60);return;}if(n.kind==2){if(n.label!=best){fail(m,61);return;}atomicAdd(reinterpret_cast<unsigned long long*>(&m->c.audited_states),1ull);return;}if(n.kind||n.term_count||n.feature<0||n.feature>=54||n.left>=at||n.right>=at||!isfinite(__uint_as_float(n.cut_bits))){fail(m,62);return;}float x=n.feature<10?float(points[row].rank[n.feature]):float((points[row].categories>>(n.feature-10))&1);at=x<__uint_as_float(n.cut_bits)?n.left:n.right;}fail(m,63);}
}
static QuotientAudit quotient_impl(const Result&r,const lp::Result&p,const std::vector<rank_disk_ledger::Node>*binary,U binary_root,const std::string&library,const std::string&model,U maximum_cells,U batch_rows,int device){need(r.complete&&r.local_semantics_audited&&r.root<r.nodes.size()&&r.source_binding==p.source.binding&&r.domain_binding==p.rank_sha256&&p.complete&&p.source_sha256==dpnative::sha256(dpnative::read_text(model))&&maximum_cells&&batch_rows&&batch_rows<=1048576&&(!binary||binary_root<binary->size()),"Apply quotient input/binding");QuotientAudit out;cu(cudaSetDevice(device));Budget b{128ull*1024*1024};Buf<Meta>meta(b,1);quotient_size<<<1,1>>>(r.domain,p.domain,maximum_cells,meta.p);cu(cudaGetLastError());auto m=meta.get(1)[0];out.CUDA_executed=true;out.owned_device_peak_bytes=b.peak;need(!m.bad,"Apply quotient domains differ");if(m.cap){out.reason="native_full_raw_quotient_cap";return out;}U cells=m.c.states,n=std::min(cells,batch_rows);std::vector<unsigned>hc;Profile prof=profile(p,hc);Buf<unsigned>cuts(b,hc.size());Buf<Node>nodes(b,r.nodes.size());Buf<Arc>arcs(b,r.arcs.size());Buf<rank_disk_ledger::Node>bnodes(b,binary?binary->size():0);Buf<Point>points(b,n);Buf<float>raw(b,n*54);cuts.put(hc.data());nodes.put(r.nodes.data());arcs.put(r.arcs.data());if(binary)bnodes.put(binary->data());check_class_nodes<<<blocks(r.nodes.size()),128>>>(r.domain,nodes.p,r.nodes.size(),arcs.p,r.arcs.size(),meta.p);profile_check<<<1,1>>>(prof,cuts.p,r.domain,meta.p);cu(cudaGetLastError());m=meta.get(1)[0];need(!m.bad,"Apply quotient layout/profile invalid");dpnative::XGBoostOracle oracle(library,model,54,7,device);need(contract(oracle,library,p,device)==r.native_contract_json,"Apply quotient native contract differs");for(U base=0;base<cells;){U count=std::min(n,cells-base);quotient_rows<<<blocks(count),128>>>(r.domain,prof,cuts.p,base,count,points.p,raw.p);cu(cudaGetLastError());const float*prob=oracle.predict_values(raw.p,count,false);if(binary)quotient_binary_compare<<<blocks(count),128>>>(points.p,count,prob,bnodes.p,binary->size(),binary_root,meta.p);else quotient_compare<<<blocks(count),128>>>(points.p,count,prob,nodes.p,r.nodes.size(),arcs.p,r.root,meta.p);cu(cudaGetLastError());m=meta.get(1)[0];if(m.bad)throw std::runtime_error("CUDA native quotient class differs: "+std::to_string(m.bad));base+=count;}need(m.c.audited_states==cells&&p.source_sha256==dpnative::sha256(dpnative::read_text(model))&&contract(oracle,library,p,device)==r.native_contract_json,"Apply quotient coverage/identity differs");out.complete=true;out.cells=cells;out.native_rows=cells;out.owned_device_peak_bytes=b.peak;out.reason=binary?"GPU_all_raw_quotient_cells_binary_native_public_class_equal":"GPU_all_raw_quotient_cells_native_public_class_equal";return out;}
QuotientAudit audit_quotient(const Result&r,const lp::Result&p,const std::string&library,const std::string&model,U maximum_cells,U batch_rows,int device){return quotient_impl(r,p,nullptr,none,library,model,maximum_cells,batch_rows,device);}
QuotientAudit audit_binary_quotient(const Result&r,const lp::Result&p,const std::vector<rank_disk_ledger::Node>&nodes,U root,const std::string&library,const std::string&model,U maximum_cells,U batch_rows,int device){return quotient_impl(r,p,&nodes,root,library,model,maximum_cells,batch_rows,device);}
U audit_terminal_probabilities(const Result&a,const Result&z,U cap,int device){need(a.complete&&z.complete&&a.local_semantics_audited&&z.local_semantics_audited&&a.source_binding==z.source_binding&&a.domain_binding==z.domain_binding&&!a.score_pool_sha256.empty()&&a.score_pool_sha256==z.score_pool_sha256&&a.native_contract_json==z.native_contract_json,"terminal comparison binding");cu(cudaSetDevice(device));Budget b{cap};Buf<State>left(b,a.states.size()),right(b,z.states.size());Buf<Meta>m(b,1);left.put(a.states.data());right.put(z.states.data());compare_terminals<<<blocks(a.states.size()),128>>>(left.p,a.states.size(),right.p,z.states.size(),m.p);cu(cudaGetLastError());auto status=m.get(1)[0];need(!status.bad&&status.c.audited_states==a.counters.terminal_states,"native terminal tuple probabilities differ or absent");return status.c.audited_states;}
}
